muxinc/elements

packages/mux-audio/package.json, packages/mux-video/package.json
From [the node.js docs](https://nodejs.org/api/packages.html#packages_package_json_and_file_extensions)
> A package.json "type" value of "module" tells Node.js to interpret .js files within that package as using ES module syntax.
Without this -- Next.js blows up
```
SyntaxError: Unexpected token 'export'
at wrapSafe (internal/modules/cjs/loader.js:988:16)
at Module._compile (internal/modules/cjs/loader.js:1036:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
at Module.load (internal/modules/cjs/loader.js:937:32)
```
With `type: "module"` in the package.json then Next.js correctly recognizes that these packages are exporting ES modules.
=> add type: "module" in package.json

README_INTERNAL.md, examples/create-react-app-with-typescript/package.json, examples/nextjs-with-typescript/package.json, examples/vanilla-ts-esm/package.json, lerna.json, package.json, packages/mux-audio-react/package.json, packages/mux-audio/package.json, packages/mux-video-react/package.json, packages/mux-video/package.json, packages/playback-core/package.json
This will make it easier to publish packages separately, each package will have its own version.
See https://github.com/lerna/lerna#independent-mode
Added 1 npm script in the root `yarn release`, this will call `lerna publish` internally 
https://github.com/lerna/lerna/tree/main/commands/publish#readme
Going from the release step list here
https://github.com/muxinc/elements/blob/main/README_INTERNAL.md
this becomes:
1. **yarn release**
Lerna will detect changed files of the packages and prompt to cut a new release (patch,minor,major,etc) of that package
*build* of package will automatically be done by the "prepublishOnly" script, *git tag* is also done automatically
2. **git push && git push --tags**
3. Edit the pushed git tag to release in GitHub and write a description
=> Make Lerna work in independent mode to publish pks

packages/mux-video/package.json, yarn.lock
This change makes the build:types script add the missing types of `CustomVideoElement` by copying them from the `src` folder to the `dist/types` folder.
Related question
https://stackoverflow.com/questions/56018167/typescript-does-not-copy-d-ts-files-to-build
=> Fix mux-video types in dist

packages/mux-video/src/index.ts
This change is needed to get Mux data working for the `<mux-video>` element.
https://github.com/muxinc/elements/blob/afa33d281bf9ddabbd53877b786466aaef2996cf/packages/playback-core/src/index.ts#L215-L215
In the case of `<mux-video>`, props is the `<mux-video>` itself so it requires a `envKey` property on it.
=> Fix Mux data integration for mux-video

packages/mux-video/src/index.ts
Adds the `type` as a property. 
I ran into an issue with an m3u8 without an extension and tried this attribute but it didn't work because the prop was not on the element.
=> Add type to mux-video for playback-core

packages/mux-player/src/index.ts
Fix start-time attr being set automatically causing video playhead for low latency to be out of sync.
=> Fix low latency live buffering in mux-player

packages/mux-player/src/styles.css
Adds width 100% internally so the player doesn't collapse with no external CSS set.
=> Fix basic css so player doesn't collapse

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/index.ts, packages/mux-player/src/video-api.ts, packages/mux-player/test/player.test.js
This change adds a `volume` and `playbackrate` attribute that sets the corresponding video property.
Changing the video properties do not reflect back to the attributes.
It also changes the behavior of the `muted` attribute so it reflects to the native video muted property in addition to defaultMuted.
=> Add custom attributes for muted, volume and playbackrate

packages/mux-player/src/styles.css
Noticed this was animating inversed compared to the controls. Should come up fast .25s, and fade out slow 1s.
=> Inverse controls background transition duration

packages/mux-player/src/styles.css
Fixes an issue where the custom element `<mxp-dialog>` was flashing on player load while it should be hidden.
=> Fix dialog flashing glitch

packages/mux-player-react/src/index.tsx, packages/mux-player/src/index.ts, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts
Setting `default-hidden-captions` on the WC element or `defaultHiddenCaptions` on the React element will have the captions not turn on by default.
=> feat: default-hidden-captions to turn off showing captions by default

packages/mux-player/src/html.ts
This change prevents setting the poster attribute if it didn't change. Re-setting the poster attribute on a video elements makes it re-request the poster url and shows a brief flash. This would also happen going from one UI view to another, small to large for example.
=> Fix poster loading multiple times on re-render

packages/mux-audio-react/package.json, packages/mux-audio/package.json, packages/mux-player-react/package.json, packages/mux-player/package.json, packages/mux-video-react/package.json, packages/mux-video/package.json, packages/playback-core/package.json
lerna sets the npm_exec_path to pretend it's npm for some scripts. This
causes, `npm-run-all` to use lerna rather than `npm` or yarn and the
`--minify` doesn't get passed automatically.
Instead, by using `--` we can force the `--minify` flag to get passed to
the underlying command.
=> chore: fixup minify build with lerna.

packages/mux-player/README.md, packages/mux-player/src/video-api.ts
Adds the readme for the WC.
Some things copied and adapted from the mux-video and MuxPlayer React docs.
=> Add first pass of mux-player WC readme

packages/mux-player/src/helpers.ts, packages/mux-player/src/index.ts, packages/mux-player/src/template.ts, packages/mux-player/src/utils.ts, packages/mux-player/src/video-api.ts, packages/mux-player/test/player.test.js
This change should make it possible to not use the setAttribute / removeAttribute methods for mux-video.
See [`0c58103` (#114)](https://github.com/muxinc/elements/pull/114/commits/0c58103b64d04a70e8791c6fb7597ed2d82d185a)
Allow for a more declarative view where things are not magically added / removed imperatively in other places in the code base.
=> Fix new attrs not taking effect

examples/nextjs-with-typescript/pages/MuxAudio.tsx, examples/nextjs-with-typescript/pages/MuxPlayer.tsx, examples/nextjs-with-typescript/pages/MuxVideo.tsx, examples/nextjs-with-typescript/pages/mux-player.tsx, examples/nextjs-with-typescript/pages/mux-video.tsx, packages/mux-audio-react/src/index.tsx, packages/mux-audio/src/index.ts, packages/mux-player-react/src/index.tsx, packages/mux-player-react/src/useObjectPropEffect.ts, packages/mux-player/src/index.ts, packages/mux-player/src/video-api.ts, packages/mux-video-react/src/index.tsx, packages/mux-video/src/CustomVideoElement.js, packages/mux-video/src/index.ts, packages/playback-core/src/autoplay.ts, packages/playback-core/src/index.ts
This change adds a couple of string options for the `autoplay` attribute/`autoPlay` prop. The exiting boolean-attribute nature of `autoplay`/`autoPlay` lives on.
Specifically:
- `muted` - will mute the player and try autoplaying. If autoplaying fails, muted state is restored and player continues as a standard click-to-play player.
- `any` - will try playing with the current options, if it fails it'll behave like `muted` above.
Happy to get alternatives to the name `any`.
In addition to the above, this switches from relying on native autoplay attribute behavior to calling `play` manually. In terms of behavior, it should be backwards compatible, but will allow us to better control this behavior going forward.
Example usage:
WC
```html
<mux-player ></mux-player>
<mux-player …
```
=> feat: Extended autoplay options

packages/mux-player/lang/en.json, packages/mux-player/lang/nl.json, packages/mux-player/package.json, packages/mux-player/scripts/esbuild.js, packages/mux-player/src/helpers.ts, packages/mux-player/src/index.ts, packages/mux-player/src/media-chrome/dialog.ts, packages/mux-player/src/styles.css, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts, packages/mux-player/src/utils.ts, packages/mux-player/test/web-test-runner.config.js, packages/mux-video/src/index.ts, packages/playback-core/src/index.ts, scripts/esbuilder/esbuilder.js, scripts/esbuilder/package.json, scripts/i18n-utils/i18n-utils.js, scripts/i18n-utils/package.json
Just wanted to open up a draft PR to start a discussion because I think we should initially remove the playback-core error handling for some reasons like:
- Currently it's possible to get in an endless loop
- It looks like this sample code shouldn't be taken literally, it requires more work on our part to handle it and check for specific conditions before to actually try and recover. The hls.js demo shows more of this, see here: https://github.com/video-dev/hls.js/blob/2635570ca3ffc6ec2c0f8ef4be84b7da9bf39443/demo/main.js#L1041-L1084
- hls.js does already retry many areas if they fail with an exponential backoff for network errors etc. and retries for appending segments see https://github.com/video-dev/hls.js/blob/master/docs/design.md#error-detection-and-handling
- A fatal network error …
=> Improve error handling

examples/vanilla-ts-esm/package.json, packages/mux-player/src/index.ts, packages/mux-player/src/template.ts, packages/mux-player/src/time-display.ts
This seems like a much more intuitive way to show time in the `<media-time-display>`. This feels like a better default. Maybe in the future we allow this to be configurable.
We don't show time display on live, so this should only impact VOD (and all my screenshots in the docs 😭 )
Thoughts?
=> Time Display: show the ascending time instead of negative time remaining

.github/workflows/ci.yml, package.json
- Adds `--ignore-scripts` because we don't want an automatic build to happen right after yarn install
- Adds a lint job 
- Separates `build` and `test` so they can run in parallel
- Adds `cache: yarn` 
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
=> Run GH action jobs in parallel, add yarn cache, add lint job

.github/workflows/cd.yml, README_INTERNAL.md, package.json
This change adds a publish job after the CI build job that automatically publishes the public packages if the version in package.json was bumped in the package. It checks against the version in the registry. 
`from-package`: https://github.com/lerna/lerna/tree/main/commands/publish#usage
`--yes`: https://github.com/lerna/lerna/tree/main/commands/publish#--yes
Adds Github Release via 
https://github.com/lerna/lerna/tree/main/commands/version#--conventional-commits
https://github.com/lerna/lerna/tree/main/commands/version#--create-release-type
Process:
```
#. Human - checkout main and make sure local main head is up to date w/upstream main
#. Human - version locally via yarn version - should use conventional commit to update versions (will tag and push commit + tags)
#. Robot - GitHub …
```
=> Add publish & release GH action

.github/workflows/cd.yml
Currently we're trying to deploy on every push to main, this will do it only on new tag pushes
=> ci: only try deploy on new tags

packages/mux-video/src/CustomVideoElement.d.ts, packages/mux-video/src/index.ts, packages/mux-video/test/player.test.js
https://github.com/muxinc/elements/pull/116 added extended autoplay support, but setting the initial attribute to one of the extended values didn't work. This fixes it so that the attribute can be set initially and not just changed after the fact.
=> fix: initial muted autoplay should autoplay muted

examples/nextjs-with-typescript/pages/MuxPlayer.tsx, packages/mux-player/package.json, packages/mux-player/src/index.ts, packages/mux-player/test/player.test.js, yarn.lock
Controls are currently defined as showing when the user is active or the player is paused.
This is more or less the MVP for this, as it only covers moving the bottom captions out of the way of the bottom controls.
The full thing would also probably need to handle the top controls as well as the middle controls.
I am also ignoring some cues depending on how they are positioned, as they are likely not going to be obscured by the bottom controls or thumbnails.
=> feat: move captions up when controls are showing

.github/workflows/cd.yml, .github/workflows/ci.yml, package.json
- Removes build from workspace level `prepare`.
- Removes redundant/unnecessary builds from ci workflows
- Adds `build:packages` to workspace level `pretest` (Can discuss tradeoffs vs. per-package `pretest` vs. independent build in github action scripts)
- No longer `--ignore-scripts` on installs, as this is brittle and may have been working in some cases as a result of previous cached installs
- `--ignore-scripts`: Do not execute any scripts defined in the project package.json **_and its dependencies_**. (From: https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-scripts)
After change approval but before merge, we will also need to change our vercel apps setup to `build:packages` on install.
=> build(build-when-needed): Update scripts to not redundantly build.

packages/mux-player/src/logger.ts
Right now devLog links are 404:
```
https://github.com/muxinc/elements/main/errors/403-playback-id-mismatch.md
```
This corrects the path:
```
https://github.com/muxinc/elements/blob/main/errors/403-playback-id-mismatch.md
```
=> fix: devLog links to GH base URL

packages/mux-video/src/CustomVideoElement.js
This change prevents forwarding custom attributes to the native video element like player-software-name, env-key, etc...
=> fix(mux-video): prevent forward custom attrs

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/styles.css, packages/mux-player/src/time-display.ts
Fixes a bug where `primaryColor` is not being applied to controls that have text (but it is being applied to controls that have icons via `--media-icon-color`.
Relates to the problem encountered here:
https://github.com/muxinc/media-chrome/discussions/198
=> fix: primary color should be also used for the text color on controls

packages/mux-player/src/index.ts, packages/mux-player/test/errors.test.js
this change prevent any non-fatal error events from leaving mux-player.
=> fix: prevent non-fatal error events propagating

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/package.json, packages/mux-player/src/styles.css, packages/mux-video/src/CustomVideoElement.js, yarn.lock
~Requires this PR in Media Chrome: https://github.com/muxinc/media-chrome/pull/205~
Upgraded media-chrome to 0.6.0
=> fix: make mux-player size based on video element

.github/workflows/release-notes.yml, package.json, packages/mux-audio-react/package.json, packages/mux-audio/package.json, packages/mux-player-react/package.json, packages/mux-player/package.json, packages/mux-video-react/package.json, packages/mux-video/package.json, packages/playback-core/package.json, scripts/create-release-notes/create-release-notes.js, scripts/create-release-notes/package.json, yarn.lock
This first pass only adds the separate GH action that can be manually kicked off from Github actions UI.
If it works good we can remove the Lerna option `--create-release github` and save the step of having to get the GH_TOKEN locally
=> ci: add release notes script and GH action

packages/mux-player/src/index.ts, packages/mux-player/src/media-chrome/dialog.ts, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts, packages/mux-player/src/utils.ts
Closes #94
this change fixes an issue where the focus would be moved to the player dialog even when the previous document focus was outside the player.
=> fix: prevent dialog from focus if outside player

examples/nextjs-with-typescript/pages/mux-audio.tsx, packages/mux-audio/src/index.ts, packages/mux-player/src/helpers.ts, packages/mux-player/src/index.ts, packages/mux-player/src/video-api.ts, packages/mux-player/test/errors.test.js, packages/mux-player/test/player.test.js, packages/mux-video/src/index.ts
With this PR, the recommended approach going forward for getting `mux-video` from `mux-player` is via `.media`. `.video` is still available for backwards compatibility.
The `.hls` property got renamed to `_hls` to discourage its use outside of elements.
=> Expose mux-video as `media` for consistency, prefix _hls

packages/playback-core/src/index.ts, packages/playback-core/src/tracks.ts
- This change fixes the issue of removing text tracks when switching playback-id's 
- Fixes a weird bug in Chrome that happens when toggling the textTrack disabled -> showing and captions are not rendered anymore. Re-adding the cues to the textTrack does the trick.
~Hls.js also had strange behavior after toggling to disabled the getters `hls.subtitleTrack` and `hls.subtiteTracks` were not correct anymore, they changed to `-1` and an empty array respectively. Added a fix for that by using the events Hls.js provides and keeping track of state in playback-core.~
^^ was caused by the change event handler not being cleaned up. this is fixed now.
=> fix(playback-core): implement track/cue management in playback-core

packages/mux-player/src/errors.ts, packages/mux-player/src/index.ts, packages/mux-player/src/logger.ts, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts, packages/mux-player/src/utils.ts, packages/mux-video/src/index.ts, packages/playback-core/src/errors.ts, packages/playback-core/src/index.ts, scripts/i18n-utils/i18n-utils.js, types/mux.d.ts
This change makes errors more uniform in mux-video by adding a `muxVideo.error` property and now the errorTranslator doesn't require a special `player_error` property because it can access that on the `mux-video` element.
=> feat: add errorTranslator prop & muxVideo.error property

packages/mux-player/src/index.ts, packages/mux-player/test/player.test.js, packages/playback-core/src/autoplay.ts, packages/playback-core/src/index.ts
With autoplay, it is possible to get the play event before
MANIFEST_LOADED happens. In those cases, we don't want to call
`hls.stopLoad` as we got a signal to continue playback.
=> fix: preload=metadata with autoplay

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/index.ts
Fixes an issue where the controls layout could be incorrect in fullscreen if the mux-player embed was small enough.
The controls mode was dependent on the mux-player dimensions when it should be dependent on the media-controller because this is the element that actually goes fullscreen.
=> fix: fullscreen controls layout

packages/mux-audio/src/CustomAudioElement.js, packages/mux-audio/src/index.ts, packages/mux-video/src/CustomVideoElement.js, packages/mux-video/src/index.ts
Fixes an issue where playback-core was init 3 times on player load.
=> fix: fix 3x init of playback-core if `src` used

packages/mux-player/src/index.ts, packages/mux-player/test/player.test.js
Clears state on `src` and `playback-token` changes
=> fix: clear state on other src related attrs

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/helpers.ts, packages/mux-player/src/media-theme-mux/media-theme-mux.ts, packages/mux-player/src/media-theme-mux/styles.css, packages/mux-player/src/template.ts, packages/mux-player/src/utils.ts
This change puts the progress bar above the controls and fixes the secondary color that broke with the theme change.
Added `--primary-color` and `--secondary-color` vars to the Mux theme.
=> fix: put progress bar above controls & fix secondary color

README_INTERNAL.md, packages/mux-player/README.md
- Having the version in the unpkg URL is good, but it just falls out of date so easily that I think it's harming us.
The downside is that if someone copy/pasta's this into their app, we will be updating their player when we release new versions without them knowing. There's some risk in that which I don't love, but I think it's better than always showing an old version in the README.
=> Update README and README_INTERNAL

packages/playback-core/src/index.ts
I forgot to prevent tracking of non-fatal errors in playback-core. this fixes that bug.
this should be the reason that we were seeing an inflated error percentage in Mux data.
however this is not the reason the error dialog was shown, this could only be caused by a "fatal" error as it's gated by a condition
https://github.com/muxinc/elements/blob/705491bafcc86d7b7f37d08faa6a248bfce8a109/packages/mux-player/src/index.ts#L281-L288
=> fix: stop tracking non-fatal errors in Mux data

packages/mux-player/package.json, packages/mux-player/src/helpers.ts, packages/mux-player/src/media-theme-mux/media-theme-mux.ts, shared/castable-video/castable-video.js, shared/castable-video/package.json, yarn.lock
This change adds support for text tracks loaded from M3U8 and simplifies the logic around text tracks.
The trackId's are now always retrieved from the remote player and the remote tracks matched with the local tracks.
=> feat: subtitles for M3U8 playlists, resume session, add cast-button

packages/mux-player/src/index.ts
This fixes the issue w/ `stream-type` warning, `start-time` not set etc. when the custom element is defined before parsing the HTML.
This unveiled another bug:
https://github.com/muxinc/media-chrome/pull/238
=> fix: attrs not available in constructor

.github/workflows/ci.yml, package.json
this change will publish canary versions automatically when things get merged on the main branch.
e.g.
```
- @mux-elements/mux-audio => 0.5.6-canary.0+df61ba9
- @mux-elements/mux-player-react => 0.1.0-canary.0+df61ba9
- @mux-elements/mux-player => 0.1.0-canary.0+df61ba9
- @mux-elements/mux-video-react => 0.4.12-canary.0+df61ba9
- @mux-elements/mux-video => 0.6.2-canary.0+df61ba9
- @mux-elements/playback-core => 0.6.1-canary.0+df61ba9
```
=> ci: add canary deploy

package.json, packages/mux-audio-react/package.json, packages/mux-audio/package.json, packages/mux-player-react/package.json, packages/mux-player/package.json, packages/mux-video-react/package.json, packages/mux-video/package.json, packages/playback-core/package.json
didn't end up using `lerna exec` because I could not get the `LERNA_PACKAGE_NAME` to expand properly in a bash command substitution.
this adds the SHA hash to the canary versions. 
also filters out beta versions when getting the latests versions because that would mess up the counter.
=> ci: add SHA hash to canary versions

examples/vanilla-ts-esm/public/mux-uploader-full.html, examples/vanilla-ts-esm/public/mux-uploader-widget.html, packages/mux-uploader/README.md, packages/mux-uploader/src/index.ts, packages/mux-uploader/src/mux-uploader-drop.ts
Some text from copying over `mux-player`'s markdown table was leftover 🍝 
Updated text to be relevant to `mux-uploader` 🌈
=> docs(mux-uploader): Update README to replace copy pasta from mux-player.

packages/mux-video/test/player.test.js
Removing emptied and waiting increase the reliability of the test since
these two events are less likely to occur on any given playback compared
to the other events that are triggered in that test.
=> test: make events dispatch test more reliable

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/helpers.ts, packages/mux-player/src/html.ts, packages/mux-player/src/index.ts, packages/mux-player/src/media-theme-mux/media-theme-mux.ts, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts, types/media-chrome.d.ts
this change adds the ability to use a different theme via a simple `theme="media-theme-goldshine"` attribute ✨ 
it required some changes to the html tagged template renderer. 
added support for unsafe static values that can make part of the HTML string to be process by the template parser.
=> feat: add ability to choose a Media Theme via attribute

.github/workflows/cd.yml
Fixes the message being null in the Slack alert because the Github event is a workflow_dispatch, not a push event.
See https://github.com/rtCamp/action-slack-notify/issues/107#issuecomment-946267002
=> ci: fix Slack alert message

.github/workflows/deprecate.yml, packages/mux-audio-react/src/index.tsx, packages/mux-audio/src/index.ts, packages/mux-uploader/src/index.ts, packages/mux-video-react/src/index.tsx, packages/mux-video/src/index.ts
When we are ready to take the plunge, we can push this branch upstream, which should allow us to then dispatch the `cd.yml` workflow on this branch to publish the `console.warn` update and then run the `deprecate.yml` workflow to deprecate the old packages on npm.
In the packages, I used `console.warn` instead of `console.error` because a `console.error` could potentially fail a build. In addition, it's logged only in the following packages to minimize the chance that there are multiple logs:
- `mux-audio`
- `mux-video`
- `mux-audio-react`
- `mux-video-react`
- `mux-uploader`
=> Mux elements scope deprecation

scripts/publish.sh
fixes the canary releases which were not updating the dependencies  that were just updated to a new canary version.
=> chore: fix canary releases - update deps too

scripts/publish.sh
this change will use the `--lazy` flag for lerna-update-wizard 
https://github.com/Anifacted/lerna-update-wizard#yarn-workspaces--lazy-installation
which should help speed up the installation of the new canary dependencies.
what I could see is that the CI builds got stuck during or after lerna-update-wizard so this might fix that
=> chore: try using yarn workspaces install w/ lazy

packages/mux-uploader-react/src/index.tsx
Was applying wrong types to the react props for MuxUploader (tl;dr - HTMLElement ref typedef crud instead of react crud)
=> fix(mux-uploader-react): Clean up typescript defs.

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/media-theme-mux/media-theme-mux.ts, packages/mux-player/src/media-theme-mux/styles.css, packages/mux-player/src/template.ts, packages/mux-player/test/template.test.js
this change adds the first step for easily hiding/showing the controls w/ CSS parts.
the controls backdrop is isolated in a separate div element to make it possible to assign a CSS part to.
=> feat: add CSS parts for controls

examples/nextjs-with-typescript/pages/index.tsx, packages/mux-audio/src/CustomAudioElement.js, packages/mux-audio/src/index.ts, packages/mux-video/src/CustomVideoElement.js, packages/mux-video/src/index.ts
fix #314
this change fixes a bug where `customVideo.nativeEl` or `customAudio.nativeEl` would be undefined in the playback core `initialize` function causing the set of the weakmap key to error.
nativeEl was undefined because the init flow of the custom media elements was not called yet.
moving the super.attributeChangedCallback to the top fixed this issue
=> fix: CustomVideo.nativeEl being null in some cases

packages/mux-uploader-react/src/index.tsx, packages/mux-uploader/src/index.ts
- Explicitly types payloads from `upchunk` events 🌈 
- Handles `endpoint` and `ref` attributes 🌈
=> Feat/mux uploader and mux-uploader-react: Improved type defs

examples/nextjs-with-typescript/pages/MuxUploader.tsx, packages/mux-uploader-react/README.md, packages/mux-uploader-react/src/index.tsx, packages/mux-uploader/README.md, packages/mux-uploader/src/index.ts
A user was getting this Typescript error when using `onError`:
After some digging, it turns out...
- [React elements](https://reactjs.org/docs/events.html) have an event handler called `onError` 💡 
- [HTML elements](https://developer.mozilla.org/en-US/docs/Web/API/Element/error_event) have an event handler called `error` 💡 
This PR renames both...
- `mux-uploader`'s custom event dispatch name from `error` to `uploaderror`; and ↔️ 
- `MuxUploader`'s error handler from `onError` to `onUploadError` ↔️ 
- Updates related `README`s and example(s) ✅ 
...which _should_ resolve the Typescript error and prevent collisions 🌈
=> fix(mux-uploader / mux-uploader-react): Error event collisions

.github/workflows/ci.yml, scripts/publish.sh
Fixes the upgrading of the dependencies after a new canary was released of a package.
potential fix by @gkatsev 
```bash
jq '. - map(select(contains("alpha") or contains("beta"))) | map(split(".")[3] | split("-")[0] | tonumber) | sort | last'
```
=> ci: fix upgrading canary deps

examples/nextjs-with-typescript/pages/MuxPlayer.tsx, packages/mux-player-react/README.md, packages/mux-player-react/src/index.tsx, packages/mux-player/README.md, packages/mux-player/src/index.ts, packages/mux-player/src/media-chrome/time-display.ts, packages/mux-player/src/media-theme-mux/media-theme-mux.ts, packages/mux-player/src/media-theme-mux/styles.css, packages/mux-player/src/styles.css, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts, packages/mux-player/test/template.test.js
This change adds the bulk of the refactor so the controls are toggled with CSS vars instead of the `controlsList` property.
IMO this feels a lot better as an API.
```html
<mux-player style="--center-play-button: none; --top-controls: none"></mux-player>
```
The manual adding of parts in the MediaTheme is replaced by a little script that adds parts automatically based on the tag names of the Media Chrome elements. This to prevent putting this extra work on the theme developer.
We can consider adding that to MediaTheme but I'd lean to not doing that to avoid surprises. 
CSS parts will also not be required once MediaChrome has the correct CSS vars for display.
=> feat: use CSS vars to toggle off elements

packages/mux-player/src/index.ts, packages/mux-player/src/utils.ts
If you do `<mux-player>.removeAttribute('playback-id')`, it'll throw an error that you can't run `.includes` on `null`.
Additionally, removing tokens or setting tokens to a non-JWT, was throwing an error as well.
Both of these bring up potential for unexpected behavior that we should think about how we want to handle. This PR doesn't change these behaviors, it only removes the errors thrown.
- What should happen if a playback-id is removed? 
- I'd expect the source to be removed, and no video can now be played
- currently, you can still continue playing the video of the last playback id
- what should happen if a token is set to an invalid value?
- I'd probably expect it to be ignored
- currently, the invalid token is used, at least for the poster image
=> fix: don't throw an error when removing tokens or playback id

examples/vanilla-ts-esm/public/mux-player.html, packages/playback-core/src/index.ts, packages/playback-core/src/util.ts
Fixes the issue where startTime was not being set on iOS when `preload=auto`, the default in some cases.
After setting currentTime 2 issues happened:
- setting currentTime did not actually work, when hitting play it would start at 0s
- the `seeking` event was fired but not the `seeked` event and subsequently no `timeupdate` events were fired causing the time range and time display to show wrong info
=> fix: startTime on iOS when preload=auto

packages/playback-core/src/index.ts
Follow-up to #325. There was a second place where we were deciding default MSE preference, which didn't get updated.
=> feat: always prefer MSE on android

.github/workflows/project.yml
This PR adds a GitHub Action that adds new issues and PRs to the project using the https://github.com/actions/add-to-project action.
Unfortunately, this requires a Personal Access Token with repo and project access. I've added one to this repo, which will expire in 30 days, but we should consider how we want that generated longer term and as we roll this action out to other repos.
=> chore: add workflow to auto-add issues to project

.github/workflows/project.yml, packages/mux-player-react/README.md, packages/mux-player/README.md, packages/mux-player/src/media-theme-mux/media-theme-mux.ts, packages/mux-player/src/template.ts, packages/mux-player/test/template.test.js
This allows folks to target it via CSS to turn off gestures.
Fixes #379.
=> feat: export gesture-layer as a part

packages/mux-player/src/index.ts
The properties were being removed, but then the functions weren't being exited early, so, they would get re-added.
=> fix: audio and nohotkeys props not being removed when set to false

examples/nextjs-with-typescript/pages/MuxPlayer.tsx, packages/mux-player/README.md, packages/mux-player/src/media-theme-mux/styles.css
~"controls shade color" is sort of a placeholder to kick off a discussion for a better name.~
You can try it out on the MuxPlayer nextjs test page.
=> feat: add --controls-backdrop-color CSS var to allow changing the backdrop color

packages/mux-player/src/template.ts, packages/mux-player/test/template.test.js
Original at https://github.com/muxinc/elements/pull/384 by @mikker
> This is needed to allow adding CSS to a nested web component via the `part()` syntax.
> 
> See [developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts)
> 
> Tested and it works.
> 
> ```
> exportparts="video: video"
> ```
> 
> ```css
> mux-player::part(video) {
>   border: 3px solid red;
> }
> ```
=> fix: Add exportparts to mux-player so we can style nested video

packages/mux-audio/src/index.ts, packages/mux-player/src/index.ts, packages/mux-player/src/video-api.ts, packages/mux-video/src/index.ts
Please use ._hls for hls.js access if you must and use .media instead of .video for consistency.
BREAKING CHANGE: remove deprecated .hls and .video props.
=> feat: remove deprecated .hls and .video props

packages/mux-player/src/styles.css
lets see if this has any bad side effects
The main motivation for this is that we put a lot of work into making sure that `<mux-player>` behaves *exactly* like the `<video>` element with regards to sizing. 
The `<video>` element by default (& `<mux-player>`, before this change) will change dimensions based on the underlying resolution. Not great for adaptive bitrate streaming.
Several folks reported this as a "bug" that the player was jumping sizes. Personally, in nearly every implementation I have done, I typically apply something like: `width: 100%; max-width: 500px;`.
I think having `<mux-player>` default to `width: 100%` is the right decision because:
- It is sort of "responsive" by default (on mobile it stretches the full viewport), on larger viewports it will be contained by …
=> improv: default width: 100% in shadowDOM

examples/nextjs-with-typescript/pages/MuxPlayer.tsx, packages/mux-audio-react/src/index.tsx, packages/mux-audio/package.json, packages/mux-audio/src/index.ts, packages/mux-audio/test/player.test.js, packages/mux-elements-codemod/package.json, packages/mux-player/package.json, packages/mux-video-react/src/index.tsx, packages/mux-video/package.json, packages/mux-video/src/index.ts, packages/mux-video/test/player.test.js, packages/playback-core/package.json, packages/playback-core/src/autoplay.ts, packages/playback-core/src/index.ts, packages/playback-core/src/preload.ts, packages/playback-core/src/types.ts, packages/playback-core/src/util.ts, packages/playback-core/test/player.test.js, packages/playback-core/test/web-test-runner.config.mjs, yarn.lock
updates the logic for preload to be updated after initial src load. e.g. from preload=none to preload=auto
this is required for starting PiP when `preload` was set to none.
I did make a change to playback-core so it returns the setAutoplay and setPreload functions in an object along with the "engine" (hls.js) because this makes it a lot easier in the React versions, don't have to mess with those hooks too much. 
in the WC versions it's also cleaner and less error prone.
less issues with importing types etc.
=> fix: subsequent preload changes

packages/mux-uploader/package.json
was seeing this in `yarn dev`. there are no `.d.ts` files in src so maybe that was the issue
> @mux/mux-uploader-react:dev: src/index.tsx(5,37): error TS2307: Cannot find module '@mux/mux-uploader' or its corresponding type declarations.
@mux/mux-uploader-react:dev: src/index.tsx(6,49): error TS2307: Cannot find module '@mux/mux-uploader' or its corresponding type declarations.
@mux/mux-uploader-react:dev: src/mux-uploader-drop.tsx(4,41): error TS2307: Cannot find module '@mux/mux-uploader' or its corresponding type declarations.
=> tools: fix uploader types

.github/workflows/cd.yml, .github/workflows/ci.yml, turbo.json
there was a bug in building where the "build" task was dependent on "clean" and "build:types" and "dev" was dependent on the "clean" task and the "^build" task. it comes down to some `dist` folders were being cleaned while another script was trying to `build` or `build:types` to the same folder.
I believe we can finally get rid of the auto clean because the build is now done in order from "dependency" to "dependents".
=> fix: turbo build clean bug

packages/playback-core/src/index.ts
When using `mux-video` and include a relative path (e.g. by using a custom domain), it will not resolve. This is because `URL()` API only accepts absolute paths and will therefor return an error causing it to fail.
You can use a base, which it uses to resolve when it's relative: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#parameters
For example `new URL("https://mux.com", "https://mave.io")` will return `https://mux.com` but `new URL("/video.m3u8", "https://mave.io")` will resolve to `https://mave.io/video.m3u8`. And  `new URL("https://mux.com", null)` will fallback to `https://mux.com`.
Another approach would be to use the `custom-domain` attribute as base, but this wouldn't work in the case when you try to proxy videos through your own server.
--- 
There is currently no …
=> Don't fail on relative paths

packages/mux-player/src/media-theme-mux/media-theme-mux.ts
Declaring the properties as colors means that the browsers will properly reject invalid values.
=> fix: use CSS.registerProperty on vars to declare them as colors

examples/nextjs-with-typescript/pages/mux-video.tsx, examples/nextjs-with-typescript/styles.css, packages/mux-player/src/index.ts, packages/mux-player/src/video-api.ts, packages/mux-player/test/player.test.js, packages/playback-core/test/player.test.js
fixes an issue in mux-player where `.preload` was an empty string as default which maps to the `auto` value.
=> fix: preload property in mux-player

package.json
To release mux-player and mux-player-react as no longer beta, we need to graduate them as per https://github.com/lerna/lerna/blob/main/commands/version/README.md#--conventional-graduate.
Since we run things in CI, we'll need a follow-up PR to remove this flag afterwards.
=> chore: graduate mux-player and mux-player-react

packages/mux-video/src/CustomVideoElement.js
this adds the CSS var to the underlying video element in addition to the media poster image for easy DX.
no need to add a separate CSS part selector.
tagging this commit as a fix intentionally.
=> fix: also add media-object-fit/position to video

examples/nextjs-with-typescript/components/renderers.tsx, examples/nextjs-with-typescript/pages/MuxPlayer.tsx, examples/nextjs-with-typescript/styles.css
Sets the height of the options section to be 100vh minus the player height and everything else.
Player height defaults to 450 and will grab the first height that's set when loaded. Will update this if the player size is changed via the "width cutoffs for reponsinve player chrome/ui" option.
=> chore: add scrollable options in nextjs/MuxPlayer

packages/mux-player-react/package.json
Follow-up on: https://github.com/muxinc/elements/pull/414
This PR removes cjs references from mux-player-react/lazy
It's got a different name so that #414 makes it into the changelog.
=> feat: Implement React.lazy with mux-player-react

packages/mux-player/src/media-chrome/dialog.ts
Firefox doesn't show a focus outline on the dialog due to no `:host-context` support. However, it doesn't seem to be necessary. Seems `:focus-visible` is working well enough.
As far as I can tell, this is the only focus outline issue that we currently have in the player, currently.
=> fix: should have focus outline on dialog's close button

packages/mux-player/src/template.ts, packages/playback-core/src/index.ts
If video title metadata isn't explicitly provided, use the video title attribute instead.
=> feat: conditionally use title for title metadata

packages/mux-player-react/src/lazy.tsx
In https://github.com/muxinc/elements/pull/465, we moved from inline styles to a style tag to reduce our styles' specificity. 
Which... um... style tags are globally scoped. So all instances of mux-player-react/lazy would receive the same background-image as the final player declared in the dom.
Oops.
This PR still uses global style tags, though it scopes background images correctly by using an inline `--mux-player-react-lazy-placeholder` css custom property.
=> fix: lazy placeholder properly scoped styles

packages/mux-audio-react/src/index.tsx, packages/mux-audio/src/index.ts, packages/mux-video-react/src/index.tsx, packages/mux-video/src/index.ts, packages/playback-core/src/autoplay.ts, packages/playback-core/src/index.ts, packages/playback-core/src/preload.ts, packages/playback-core/src/types.ts
- this adds an async effect for init playback core and loading the media for the mux-video and mux-audio custom elements.
- made the `mediaEl` required in playback-core making some code and types easier.
=> fix: add async effect for loading media

packages/mux-player/src/html.ts, packages/mux-player/test/html.test.js
not a reference cache key related #517
=> fix: duplicate render by using value cache key

packages/mux-player/src/html.ts, packages/mux-player/src/template.ts, packages/mux-player/test/template.test.js
this is better as the template element itself is not in the DOM for all to see.
and it doesn't clone the template with each render which it does if it is included as a DocumentFragment like before.
=> fix: allow setting theme template via property

packages/mux-player/src/helpers.ts, packages/mux-player/test/helpers.test.js, packages/mux-player/test/player.test.js
- use `webp` format for `thumbnail` and `storyboard`
Even with signed URLs, this works with the same token. See:
Thumbnail token:
- [thumbnail jpg](https://image.mux.com/qIJBqaJPkhNXiHbed8j2jyx02tQQWBI5fL6WkIQYL63w/thumbnail.jpg?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFkamYzb2JpYURUcEF0QVlpS3NCMkpvRlkwMXBpbEJMTHdYcUQzaHpJYURJIn0.eyJleHAiOjE5NjE2NTkzMzAsImF1ZCI6InQiLCJzdWIiOiJxSUpCcWFKUGtoTlhpSGJlZDhqMmp5eDAydFFRV0JJNWZMNldrSVFZTDYzdyJ9.zQ0tDimpgu7nsT9Tb7GBgitMpYSbLBodwS-fSc7U0K0WT-giCUgxXXSqXquwpHMjEEfSuCsCU3Y1gq2P7WaJUBGTOTLKT5GOwyhjeoJzTPXEQqW7T-tpKXhjEDVwy_H2UPNVdA9ZALos5R9rrWyiTQA53sxT56FWy-IhvaISpiB16nzankRKCAo98kh6lloexE8p3lXnUhLwIK8Hqco4hRmHSmWqUndnJrbq0_kag0o8R0drffSMj6CvKas8_f6v3MtHXDhW0JkJ1TZKwICt7W-jrSyMfhgAb9wltBCUXdNHYvQTXkFfFnsI1R-BuZodQL2zN3pVBqzuhQA0UPADMw)
- …
=> fix: use webp format for less bandwidth

packages/mux-player/REFERENCE.md
Mux Player supports `--media-object-size` and `--media-object-position` css variables but doesn't have them documented. This just adds them to the `REFERENCE.md` file.
See: #455 for the original feature PR.
=> docs(mux-player): Document media-object-size and media-object-position css variables

packages/mux-player/package.json, packages/mux-player/src/index.ts, packages/mux-player/src/media-theme-mux.html, packages/mux-player/src/template.ts, packages/mux-player/test/player.test.js, packages/mux-player/test/template.test.js, yarn.lock
requires https://github.com/muxinc/media-chrome/pull/448
requires a Media Chrome upgrade that makes the theme attributes (if there are any) overwrite the ones supplied by the media controller.
`stream-type` is an example of this, we still want to be able to override this and also set it before it is computed in Media Chrome.
`audio` will have to be removed as a supplied param by media-controller because we set this ourselves, that was my bad.
https://github.com/muxinc/media-chrome/blob/main/src/js/media-theme-element.js#L12
=> fix: use new MC template syntax

examples/nextjs-with-typescript/pages/MuxPlayerTheme.tsx, examples/nextjs-with-typescript/pages/index.tsx, examples/vanilla-ts-esm/public/index.html, examples/vanilla-ts-esm/public/mux-player-theme.html, packages/mux-player-react/src/index.tsx, packages/mux-player/package.json, packages/mux-player/src/index.ts, packages/mux-player/src/media-theme-mux.html, packages/mux-player/src/styles.css, packages/mux-player/src/template.ts, packages/mux-player/src/types.d.ts, packages/mux-player/test/player.test.js, yarn.lock
currently packaging of MC themes is done by wrapping them in a web component see
https://github.com/muxinc/media-chrome/blob/main/src/js/themes/media-theme-youtube.js
this change adds some logic that checks (when the `theme` attribute is set) if the `media-theme-x` is defined as a custom element and uses its template for theming.
test url: https://elements-demo-nextjs-git-fork-luwes-mc-theme3-mux.vercel.app/MuxPlayerTheme
=> feat: add way to set and render MC themes

.github/workflows/ci.yml, examples/nextjs-with-typescript/pages/MuxPlayerTheme.tsx, packages/mux-player/package.json, packages/mux-player/test/errors.test.js, packages/mux-player/test/player.test.js, packages/mux-player/test/web-test-runner.config.mjs, yarn.lock
Fixes the big blocker for running tests in Firefox and Safari. This is an error from usage of ResizeObserver in media-chrome. For whatever reason, Firefox and Safari throw an error around the loop limit being exceeded. Currently having those errors ignored in `player.test.js`.
Enabled running tests in firefox and webkit via `playwright`. Can be done by running `yarn test --all`.
TODO, in no particular order:
=> Cross browser tests

package.json, turbo.json
reasoning is that build:types has a dependency on the polyfills to be there.
build has a depdency on build:types so we can remove some `copypolyfills` strings
=> test: fix turbo dependency copy polyfills

packages/mux-uploader/src/layouts/block.ts, packages/mux-uploader/src/mux-uploader.ts, packages/mux-uploader/test/uploader.test.js
If a user prefers to use `<mux-uploader-drop>` outside of the `<mux-uploader>` element, we should allow them to disable the default `<mux-uploader-drop>` element rendered as a child of `<mux-uploader>`
This adds a `noDrop` attribute which would modifiy the defauly layout to render a `div` element as a wrapper instead of `<mux-uploader-drop>`
=> fix(mux-uploader): conditionally render mux-uploader-drop

packages/mux-uploader/src/mux-uploader-drop.ts, packages/mux-uploader/src/mux-uploader-progress.ts
Introducing the `<mux-uploader-drop>` element as a default presentation brought a few problems with how the elements were styled as the upload progressed. This PR fixes those regressions.
=> fix(mux-uploader): fixing dropzone styling regressions

examples/nextjs-with-typescript/pages/MuxPlayerTheme.tsx, examples/vanilla-ts-esm/public/mux-player-theme.html, packages/mux-player-react/src/index.tsx, packages/mux-player/src/index.ts, packages/mux-player/src/template.ts, packages/mux-player/test/player.test.js
adds `theme-` prefixed attributes support for forwarding to the underlying `media-theme` element.
=> Player `theme-*` attributes & `themeProps` property

packages/mux-uploader/src/layouts/block.ts, packages/mux-uploader/src/mux-uploader.ts, packages/mux-uploader/test/uploader.test.js
This PR adds support for conditional rendering of `mux-uploader` components, including `nodrop`, `noprogress`, `nostatus`, and `noretry`. By passing the `MuxUploader` element to the `blockLayout` function, users can now choose to hide specific components based on their needs.
Usage:
```html
<mux-uploader nodrop nostatus></mux-uploader>
```
In this example, `<mux-uploader>` will be rendered without the drop area and status components, while keeping the progress and retry components.
=> feat(mux-uploader): conditional render based on attributes

packages/mux-uploader/README.md, packages/mux-uploader/src/mux-uploader-file-select.ts, packages/mux-uploader/src/mux-uploader.ts
This PR removes CSS variables from the Mux Uploader package to simplify the styling and improve the maintainability of the code. Changes include:
- Removed CSS variables for button background color, border, padding, and border radius in favor of hardcoded values.
- Removed CSS variables for button hover text and background in favor of hardcoded values.
- Removed CSS variables for button active text and background in favor of hardcoded values.
- Removed the `:host` block that contained CSS variables for font family, font size, and background color.
=> Removing CSS in favor of slots/individual components

packages/mux-uploader/src/mux-uploader.ts, packages/mux-uploader/test/uploader.test.js
This PR adds support for the `maxFileSize` feature provided by UpChunk. We introduce a new attribute called `max-file-size` for the `mux-uploader` custom element. This attribute allows users to set a maximum file size limit for the uploaded files. When the `max-file-size` attribute is set, its value will be passed down to UpChunk's `createUpload` method as the `maxFileSize` property.
- Added a `maxFileSize` getter and setter to the `MuxUploaderElement` class
- Updated the `handleUpload` method to conditionally include the `maxFileSize` property in the options object passed to UpChunk's `createUpload` method
By supporting UpChunk's `maxFileSize` feature, developers can now easily enforce file size restrictions directly from the `mux-uploader` custom element, improving the user experience …
=> feat(mux-uploader): support max file size

examples/nextjs-with-typescript/package.json, packages/mux-audio-react/package.json, packages/mux-elements-codemod/package.json, packages/mux-player-react/package.json, packages/mux-uploader-react/package.json, packages/mux-uploader/package.json, packages/mux-video-react/package.json, yarn.lock
This PR adds all transitive dependencies. As you can select pnpm mode in node linker config (which introduced in yarn v3), I recommend that you update to yarn v3 whenever possible and use that mode. It's the only non-pnpm package manager option that can prevent problems with transitive dependencies out of the box. And it's much more stable than pnpm.
There is already a not bad explanation, so just quote[^1] that:
> ### Why not NPM or YARN (v1)?
> NPM uses flattened node_modules. The flattened dependency results in many issues, such as:
The algorithm for flattening a dependency tree is complex
Some of the packages have to be duplicated inside another project's node_modules folder.
Modules have access to packages they do not depend on
Let's explain this with a basic example. One of your …
=> Correct package dependencies

package.json, turbo.json, yarn.lock
Our team uses Mux Player, Next.js and Turborepo in production, and we realized that we were uploading a large amount of useless remote cache to Vercel because we didn't ignore this one 😱
I believe this reduces post-build cache upload time and build cache download time somewhat 🤷‍♂️
=> Turborepo related chores

packages/mux-player/src/styles.css
if the player is set to rtl direction, some functionality breaks, so, we want to force it to always be ltr
If we set it on the :host, then if someone sets direction on mux-player itself, it'll get overridden. So, instead, to force it to always be ltr, we set it on the media-theme element itself.
=> fix: force theme to be ltr direction

packages/mux-player/src/index.ts, packages/mux-player/src/media-theme-mux.html, packages/mux-player/test/player.test.js, packages/mux-video/src/CustomVideoElement.js
While a single solution for all browsers is nice, we've had some reports of captions briefly showing up at the top of the video display area, which is unexpected. Therefore, we should switch back to the pseudo element technique for Chrome and Safari while keeping the programmatic line technique in use for Firefox, since it doesn't have anything else available.
This uses a transform on the text track container pseudo element and will transition it at 0.433s so that the transition is nice and smooth. This number was borrowed from the WebVTT specification. Also, when hiding, add a slight delay.
Fixes #660.
=> fix: use webkit pseudo element for captions movement, where available

packages/mux-uploader/src/mux-uploader.ts, packages/mux-uploader/test/uploader.test.js
We were previously resetting the state (attributes) whenever we set the endpoint. Since changing the endpoint does not impact the current upload, we should only (currently) reset the state based on retries. This is especially relevant when using async functions for our endpoint value, since they must (unnecessarily) be referentially identical (e.g.In React, the endpoint must have a stable reference, unnecessarily requiring `useCallback` to avoid unintentionally resetting mux-uploader state attributes based on a re-render.).
=> fix(mux-uploader): Don't reset state when endpoint is changed.

packages/mux-uploader/src/mux-uploader-drop.ts, packages/mux-uploader/src/mux-uploader-file-select.ts, packages/mux-uploader/src/mux-uploader.ts, packages/mux-uploader/test/uploader-drop.test.js, packages/mux-uploader/test/uploader.test.js
This allows for additional styles to be applied on more components based on the current upload state of the selected file.
=> chore(mux-uploader): Reflect state across multiple components

packages/mux-player/package.json, yarn.lock
Bumps the player package media-chrome dependency to 1.2.1.
This would allow using recent media chrome features (like list box enhancements) in the new default player theme.
=> chore: bump media chrome to 1.2.1 for player

packages/mux-player/src/index.ts
Confirmed locally on both next app (theme page) and vanilla by adding a div with a corresponding id. Since these are valid use cases for themes and since the error scenario is fairly impenetrable, this feels like a light lift devex improvement imo.
=> fix(mux-player): Only match theme by id if element is a template.

packages/mux-player/package.json, yarn.lock
Includes fix for themes not rendering controls at small sizes
=> chore: Bump media chrome to 1.4.2

packages/mux-audio/src/index.ts, packages/mux-video/src/index.ts
Currently, we do an "unload"/teardown of core (and everything that happens in it/is created by it "under the hood") whenever our custom media elements are disconnected from the DOM. Ideally, this would not be the way we handle cleanups, as we're currently treating disconnect as a "`destroy()`" method. This causes issues with more advanced UIs/use cases, especially common in app frameworks where an element may be moved around the DOM for UI/UX purposes without the intention of destroying it. Unfortunately, it looks like we have some dangling references that result in a fairly large memory footprint per media element if we don't do this teardown. As a "middle ground" solution until we can identify a reasonable and reliable resolution of this larger memory management GC issue, we will simply …
=> fix(mux-video,mux-audio): reload core on DOM connect

packages/mux-player/src/template.ts, packages/mux-player/src/themes/2023/2023.html, packages/mux-player/src/themes/classic/classic.html, packages/mux-player/test/template.test.js
=> feat: export control bars part for styling

packages/playback-core/src/index.ts, packages/playback-core/src/media-tracks.ts
reverts a bug fix in https://github.com/muxinc/elements/pull/759
it was a good patch but it prevented the audio tracks API to be populated if there was just 1 audio track.
it's still expected that with 1 audio track, the API returns an item for video.audioTracks[0].
this change adds that back in.
the root issue in hls.js I believe was that we were trying to select an audio track with a string ID and hls.js works with numeric ID's.
this change also adds a check if hls.js audioTracks has the ID to which the player tries to switch.
=> fix: audio track API for 1 track

packages/mux-player/src/themes/gerwig/gerwig.html
The bg gradients can sometimes swallow clicks. At small sizes the bottom one starts to encroach on the center controls and can swallow clicks if they're towards the bottom of the center play and skip buttons. This could also be fixed by tweaking z-indexes but that could have other effects.
=> fix: Don't allow clicks on bg gradients

packages/mux-player/src/themes/gerwig/gerwig.html
To match the rest of the theme I removed the opacity on the selected items as we hadn't used shades of the accent color elsewhere. This also nicely increases the contrast.
<br>
=> fix(mux-player): Use solid accent color in rate menu

packages/mux-player/package.json, packages/mux-player/src/themes/classic/classic.html, packages/mux-player/src/themes/gerwig/gerwig.html, yarn.lock
The listbox options of Gerwig were not the same height when selected vs not selected.
The new range requires padding values that can be calculated.
=> fix: upgrade MC + style tweaks

packages/mux-player-react/src/useIsBrowser.ts
There's a mis-match with the player versions, this will force them to match.
=> feat(mux-player-react): Force bump

examples/nextjs-with-typescript/pages/MuxPlayer.tsx
probably missed when we flipped the switch to `gerwig`.
=> chore: next.js MuxPlayer demo page missing import for classic theme.

packages/mux-player/src/styles.css, packages/mux-player/src/themes/gerwig/gerwig.html
This feature adds "opt in" controls to the "gerwig" (default 2023) Mux Player theme via CSS. This applies to the "extra small" UI (<470px width). To "opt in", you must set the relevant display CSS variable from its default (`none`) to `inline-flex`. The most relevant variables are:
- `--time-display`
- `--playback-rate-selectmenu`
- `--pip-button`
While there are "center controls" for play/seek back/seek forward, you may also "opt in" to showing those in the control bar via:
- `--play-button`
- `--seek-backward-button`
- `--seek-forward-button`
**NOTE:** "Under the hood," the gerwig theme actually relies on the more specific "bottom" CSS vars (e.g. `--bottom-time-display`). Due to CSS precedence rules, setting these values will be harder, as the theme-based CSS selector may have a higher …
=> feat(mux-player): allow forcibly showing buttons that we usually hide at small sizes

examples/vanilla-ts-esm/package.json, packages/mux-active-viewer-count/package.json, packages/mux-audio-react/package.json, packages/mux-audio/package.json, packages/mux-elements-codemod/package.json, packages/mux-player-react/package.json, packages/mux-player/package.json, packages/mux-player/scripts/build-themes.mjs, packages/mux-uploader-react/package.json, packages/mux-uploader/package.json, packages/mux-video-react/package.json, packages/mux-video/package.json, packages/playback-core/package.json, scripts/esbuilder/esbuilder.js, scripts/esbuilder/package.json, shared/test-esm-exports/package.json, yarn.lock
upgrades esbuild everywhere and adds logs of the builds to esbuilder and the themes build script
uses the new esbuild API since v0.17.0 https://github.com/evanw/esbuild/releases/tag/v0.17.0
=> chore: upgrade esbuild + add logging to JS api

examples/nextjs-with-typescript/pages/MuxPlayer.tsx, examples/nextjs-with-typescript/pages/MuxPlayerLazy.tsx, examples/nextjs-with-typescript/pages/mux-player.tsx, examples/vanilla-ts-esm/public/mux-player-audio-tracks.html, examples/vanilla-ts-esm/public/mux-player-audio.html, examples/vanilla-ts-esm/public/mux-player-cuepoints.html, examples/vanilla-ts-esm/public/mux-player-poster-slot.html, examples/vanilla-ts-esm/public/mux-player-renditions.html, examples/vanilla-ts-esm/public/mux-player-theme-classic.html, examples/vanilla-ts-esm/public/mux-player-theme.html, examples/vanilla-ts-esm/public/mux-player.html
this script is not needed anymore, castable-video loads it automatically.
also if the script is loaded twice it causes an error in the console but doesn't break the player or page.
this is only an issue when the users script is loaded after castable-video already appended its own script.
Next.js script tag is loaded afterInteractive, that's why it is causing the error log.
if it's loaded before castable-video checks that and prevents loading
see https://github.com/muxinc/castable-video/blob/0e5f322d4d1b7dd53215e4102d5712f8aa2721aa/castable-utils.js#L50-L50
=> examples: remove unneeded cast framework script

examples/vanilla-ts-esm/public/mux-player-theme-classic.html, examples/vanilla-ts-esm/public/mux-player.html, package.json, packages/mux-player/scripts/build-themes.mjs, packages/mux-player/src/index.ts, packages/playback-core/src/util.ts, scripts/esbuilder/esbuilder.js, yarn.lock
=> fix: target-live-window unneeded sprout

packages/mux-player/tsconfig.json, packages/mux-video/package.json, packages/mux-video/src/index.ts, packages/playback-core/src/types.ts, packages/playback-core/tsconfig.json, yarn.lock
this fixes a TS issue where if one imported the media-tracks mixin the HTMLMediaElement type would get all the new media tracks methods automatically. it's probably not a huge deal but right is right.
related PR https://github.com/muxinc/media-tracks/pull/12
if you do mixin media tracks in the global HTMLMediaElement you must import or include
`media-tracks/dist/global.d.ts` which will merge in the media-tracks methods...
cc @cjpillsbury
=> fix: media-tracks types not polluting global HTMLMediaElement

packages/playback-core/src/index.ts
In other words, seekable should only apply holdback (baked into `hls.liveSyncPosition`) while the live stream is "active"/"still live".
=> fix(playback-core): Make sure we do not apply holdback to seekable when live streams have ended.

packages/mux-player-react/src/lazy.tsx
Before suspense loads the player bundle, we use `--mux-player-react-lazy-placeholder:url({placeholder})` to show the placeholder. However, `{placeholder}` wasn't showing in some cases (especially with the new `@mux/blurup` library) because it was an invalid URL. `'{placeholder}'` is more robust, so this PR adds those quotation marks.
=> fix(mux-player-react/lazy): display placeholder before JS load

examples/nextjs-with-typescript/pages/MuxUploaderSeparateComponents.tsx, examples/nextjs-with-typescript/pages/index.tsx, packages/mux-uploader-react/src/index.tsx, packages/mux-uploader-react/src/mux-uploader-drop.tsx, packages/mux-uploader-react/src/mux-uploader-file-select.tsx, packages/mux-uploader-react/src/mux-uploader-progress.tsx, packages/mux-uploader-react/src/mux-uploader-retry.tsx, packages/mux-uploader-react/src/mux-uploader-status.tsx
fixes #856 
Also adds a basic example of using Mux Uploader React subcomponents to nextjs demo app: https://elements-demo-nextjs-git-fork-cjpillsbury-fix-mux-up-6f414e-mux.vercel.app/MuxUploaderSeparateComponents
=> fix: Add className types for all Mux Uploader react subcomponents.

packages/mux-player/src/styles.css, packages/mux-player/src/template.ts, packages/mux-player/test/player.text-tracks.test.js
Since DRM-protected content requires a custom receiver app for casting (https://support.google.com/widevine/answer/6072130?hl=en), hide the cast button by default whenever we encounter a drm token. Went ahead and introduced a simple generic concept (props-driven css) and a pattern (internal css vars as defaults) that we can conform to for these cases.
=> fix(mux-player): Hide cast button by default when using DRM.

examples/nextjs-with-typescript/package.json, packages/mux-audio/package.json, packages/mux-player/package.json, packages/mux-video/package.json, packages/playback-core/package.json, yarn.lock
fix #927
related:
https://github.com/muxinc/next-video/issues/254
https://github.com/video-dev/hls.js/issues/6201
=> fix: upgrade hls.js, custom-media-element, etc.

packages/playback-core/src/index.ts
This would definitely be an edge case, but is hypothetically possible given the async aspects at play here. tl;dr - `buffered` time range length may still be `0` when one of the several events that invoke `maybeDispatchEndedCallback()` is dispatched. This ensures that we don't end up in cases where we are assuming `buffered.length > 0` and also ensures that we treat an empty buffered as under-determined for "pseudo-ended" cases.
=> fix(playback-core): pseudo-ended eval case where media is not attached.

examples/nextjs-with-typescript/pages/MuxUploader.tsx, packages/mux-uploader-react/src/index.tsx, packages/mux-uploader/src/layouts/block.ts, packages/mux-uploader/src/mux-uploader-drop.ts, packages/mux-uploader/src/mux-uploader-file-select.ts, packages/mux-uploader/src/mux-uploader-pause.ts, packages/mux-uploader/src/mux-uploader-progress.ts, packages/mux-uploader/src/mux-uploader-retry.ts, packages/mux-uploader/src/mux-uploader-status.ts, packages/mux-uploader/src/mux-uploader.ts
Primary purpose of this PR is to account for changes to props/attrs after initial load. Because of the underlying architecture, there are still potential edge cases around state vs. UI mismatches after upload has begun (e.g. pausing state + progress state, though progress will update on the next progress event to handle some of those cases).
=> feat: clean up type attr. Handle dynamic updates better.

packages/mux-player/package.json, packages/mux-player/src/themes/classic/classic.html, packages/mux-player/src/themes/gerwig/gerwig.html, yarn.lock
Blocked by https://github.com/muxinc/media-chrome/pull/946
Fixes https://github.com/muxinc/elements/issues/863
Smoke tested 👍  on both iOS Safari and iOS Chrome, plus desktop browsers for regression testing.
=> fix(mux-player): use CSS to disable subtitle shifting for iOS in fullscreen.

packages/mux-player/src/themes/gerwig/gerwig.html
when turning off hardware acceleration on Chrome it was reported that the Mux player UI became laggy.
I found one other user on Stackoverflow with the same issue:
https://stackoverflow.com/questions/12991164/maintaining-the-final-state-at-end-of-a-css-animation#comment118487774_12991203
Seems like part of the explanation is found here
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode#forwards
> Animated properties behave as if included in a set [will-change](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) property value. If a new stacking context was created during the animation, the target element retains the stacking context after the animation has finished.
=> fix: css animation forwards causing UI lag

examples/nextjs-with-typescript/pages/MuxPlayerChapters.tsx, packages/mux-player/src/index.ts, packages/mux-video/src/index.ts
When we released chapters we unified the chapter and cuepoint types under the hood, making both support an optional `endTime` with cuepoints still supporting the legacy shape using `time` instead of `startTime`. Our `addChapters` and `addCuePoints` methods on the player don't use these new types though. `endTime` is currently required by the `addChapters` method, but shouldn't be, and only the legacy type is required by `addCuePoints`.
These changes re-use our existing internal types for `Chapter` and `CuePoint` for the external interface.
Fixes #947
=> fix: chapters and cuepoints interface doesnt reflect internal types

packages/mux-active-viewer-count/test/web-test-runner.config.mjs, packages/mux-audio/test/web-test-runner.config.mjs, packages/mux-player/test/web-test-runner.config.mjs, packages/mux-uploader/package.json, packages/mux-uploader/test/web-test-runner.config.mjs, packages/mux-video/test/web-test-runner.config.mjs, packages/playback-core/test/web-test-runner.config.mjs
locally this seemed to do the trick. issues caused by the new headless mode I suppose
=> tests: fix tests by using Chrome --headless=old

packages/mux-player/src/themes/gerwig/gerwig.html
They have no use during pre-playback, they're an artefact of the mobile designs that we overlooked.
=> fix(mux-player, mux-player-react): Remove seek buttons from mobile pre-playback UI

packages/mux-uploader/REFERENCE.md
Came up in a support query that our docs were ambiguous about what is actually returned on a `success` callback when mux-uploader fires a `success` event. What you actually get is a `CustomEvent` with a `detail` property set to `null`.
=> docs(mux-uploader): Explicit return value of null in success callback reference

packages/mux-player/src/themes/gerwig/gerwig.html
We weren't showing many buttons on mobile for live audio. This adds the play, live and mute button, but keeps the volume slider for larger views.
=> fix(mux-player): add buttons to mobile live audio view

packages/mux-player-react/src/themes/classic.ts, packages/mux-player-react/src/themes/gerwig.ts, packages/mux-player-react/src/themes/microvideo.ts, packages/mux-player-react/src/themes/minimal.ts, packages/mux-player/src/themes/gerwig/gerwig.html
Wanted to force a major version bump and noticed these ts-ignore seemed to no longer be needed anyway.
=> chore(mux-player,mux-player-react)!: major version update

packages/playback-core/package.json, yarn.lock
**NOTE**: Although our new semver matchers allow for newer versions of mux-embed to be installed (so long as yarn.lock, package-lock.json, package-shrinkwrap.json of uses don't get in the way), we should still update the min version, since 5.3.0  will break Mux Player (et al.) for some build setups for integrators.
fixes #908
=> fix(playback-core): Explicitly moving minimum version of mux-embed to 5.3.1 due to build issues in more complex build setups.

packages/playback-core/src/index.ts
Suspect this is the root cause of (non-fatal) error logs showing up in test runs (including CI).
=> fix(playback-core): Make sure seekable TimeRanges is populated when updating state.

packages/mux-active-viewer-count/package.json, packages/mux-audio-react/package.json, packages/mux-audio/package.json, packages/mux-player-react/package.json, packages/mux-player/package.json, packages/mux-uploader-react/package.json, packages/mux-uploader/package.json, packages/mux-video-react/package.json, packages/mux-video/package.json, packages/playback-core/package.json
fixes https://github.com/muxinc/elements/issues/1011
=> fix: move package exports default condition to be last

examples/nextjs-with-typescript/pages/MuxPlayer.tsx, packages/playback-core/src/index.ts, packages/playback-core/src/min-cap-level-controller.ts
Implements a custom `CapLevelController` that ensures we never cap to 480p (portrait or landscape)
**To test:**
1. Go to: https://elements-demo-nextjs-git-fork-cjpillsbury-feat-custo-7d5867-mux.vercel.app/MuxPlayer
2. In the config UI, use the `width` input to set `MuxPlayer`'s `width` to something smaller than 480p (keep in mind dpp, so you may want to choose something small like `200`
3. In the config UI, use the `playbackId` input to set the desired `playbackId` (or choose one from the dropdown)
4. Confirm that quality doesn't look sad
- **NOTE:** For advanced/programmatic confirmation, you can e.g. open the browser's dev tools beforehand, go to the network tab, filter by .m3u8, and make sure the video media playlists being requested match a resolution > 480p from the response content …
=> feat(playback-core): custom cap level controller

.github/release-please/.release-please-manifest.json, .github/release-please/release-please-config.json, .github/workflows/cd.yml, README_INTERNAL.md, package.json, scripts/publish-packages/package.json, scripts/publish-packages/publish-packages.js, scripts/publish.sh, yarn.lock
and use Turbo for task runner.
This change replaces Lerna with https://github.com/googleapis/release-please for releasing our Mux elements packages.
We started using Lerna right before it was deprecated and then saved and taken over by nrwl https://github.com/lerna/lerna/issues/3121
Since then we haven't updated from v4, current version is v8, to avoid breaking things. 
With the creation of the media-elements monorepo and the player.style monorepo we started using Release Please which turned out to be a good experience. There is no local version bump needed and manual GH action triggers etc. but keeps the good parts like use of conventional commits and a confirmation step with an auto created release PR.
Canaries are still done via the publish.sh script but I'm happy to move that over to …
=> chore: replace Lerna w/ Release Please

.github/workflows/ci.yml
this also prevents releasing canaries at the same time as when a production release is made
=> chore: no CI for release please bot

packages/playback-core/src/index.ts, packages/playback-core/src/min-cap-level-controller.ts
`CapLevelController` doesn't seem to be exported directly in the CJS bundle, 
https://cdn.jsdelivr.net/npm/hls.js@1.5.17/dist/hls.js
See in
https://cdn.jsdelivr.net/npm/@mux/playback-core@0.28.0/dist/index.cjs.js
```js
var ye=require("hls.js"),Z=class Z extends ye.CapLevelController{constructor(t){super(t)}get levels(){var t;return(t=this.hls.levels)!=null?t:[]}getValidLevels(t){return this.levels.filter((r,n)=>this.isLevelAllowed(r)&&n<=t)}getMaxLevel(t){let r=super.getMaxLevel(t),n=this.getValidLevels(t);if(!n[r])return r;let o=Math.min(n[r].width,n[r].height),a=Z.minMaxResolution;return o>=a?r:ye.CapLevelController.getMaxLevelByMediaSize(n,a*(16/9),a)}};Z.minMaxRe
```
=> fix: cap level controller import in cjs build

examples/nextjs-with-typescript/pages/index.tsx, examples/nextjs-with-typescript/pages/mux-video-react.tsx, packages/mux-video/package.json, packages/mux-video/src/react.ts, yarn.lock
related https://github.com/muxinc/next-video/pull/303
motivation:
- we use the React wrapper with custom mux-video element in 2 places (player.style and next-video soon)
- open issue asking for support (https://github.com/muxinc/elements/discussions/910)
=> feat: add `@mux/mux-video/react` import

packages/mux-player/src/themes/classic/index.ts, packages/mux-player/src/themes/gerwig/index.ts
Fix: https://github.com/muxinc/elements/issues/1055
My fix is based on importing media-chrome elsewhere.
=> fix: Mux-player imports

packages/mux-audio/package.json, packages/mux-player/package.json, packages/mux-video/package.json, packages/playback-core/package.json, yarn.lock
For details on the bug and fix, see:
- https://github.com/video-dev/hls.js/issues/6947
- https://github.com/video-dev/hls.js/pull/6946
Full smoke testing of the issue requires a Windows machine with Edgeium and Widevine DRM disabled. If available, please reach out for details on playback ids + tokens to test.
=> fix(playback-core): Update hls.js version to fix multi-DRM playready bug.

examples/nextjs-with-typescript/pages/MuxPlayerPosterSlot.tsx, examples/vanilla-ts-esm/public/mux-player-poster-slot.html, packages/mux-active-viewer-count/test/web-test-runner.config.mjs, packages/mux-audio/test/web-test-runner.config.mjs, packages/mux-player/package.json, packages/mux-player/src/styles.css, packages/mux-player/src/themes/gerwig/gerwig.html, packages/mux-player/test/web-test-runner.config.mjs, packages/mux-uploader/test/web-test-runner.config.mjs, packages/mux-video/test/web-test-runner.config.mjs, packages/playback-core/test/index.test.js, packages/playback-core/test/tracks.test.js, packages/playback-core/test/web-test-runner.config.mjs, yarn.lock
related https://github.com/muxinc/media-chrome/pull/1055
this should fix the flicker that could happen between showing the thumbnail and showing the whole theme w/ thumbnail.
=> fix: upgrade MC, fix theme flicker

packages/mux-uploader/package.json, yarn.lock
to [v3.5.0](https://github.com/muxinc/upchunk/releases/tag/v3.5.0)
- fix: handle edge case for resuming chunk upload case where multiple chunks have previously been uploaded. by @cjpillsbury in [#141](https://github.com/muxinc/upchunk/pull/141)
- feat: dispatch error when endpoint promise fails to provide a string by @decepulis in [#151](https://github.com/muxinc/upchunk/pull/151)
=> Update upchunk to v3.5.0

examples/vanilla-ts-esm/public/mux-uploader-modal.html, packages/mux-uploader-react/src/mux-uploader-progress.tsx, packages/mux-uploader/REFERENCE.md, packages/mux-uploader/src/mux-uploader-progress.ts
- `--progress-bar-background-color` (I know it's technically configuring `background`, but, following the example of `--progress-bar-fill-color`, I called it `background-color`)
- `--progress-bar-border-radius`
- `--progress-bar-box-shadow` (I don't even know what this property does, but it felt like it should be configurable, like the others)
Also:
- Demo new props in mux-uploader-modal example
- Added missing `--progress-radial-fill-color` on React style props
=> feat: add additional custom properties to mux-uploader progress bar

packages/playback-core/src/index.ts
- This only happens when using FairPlay + Safari + Native HLS playback
- There are two `generateRequest()` for FairPlay DRM + native playback, but there should only be one
- The second causes an error/promise rejection due to the state of the `session`
- This doesn't have any "real" consequences for playback, because the first `generateRequest()` was valid and is used downstream for server request + response + session update
- It should still be resolved because
- It's wrong
- It may propagate out to error tools like Sentry, resulting in false positives for error monitoring
=> fix(playback-core): Remove redundant FPS DRM generateRequest() for native playback.

.github/workflows/cd.yml
This is to avoid painful consequences of failures wrt release-me side effects.
**NOTE:** Ideally, we'd improve this to not rely on brute forcing/probabilistic assurances, but taking this approach per suggestion from @luwes at least as a stopgap improvement.
=> build: Make CD github action look more like CI github action for tests (uses playwright and retries).

packages/playback-core/src/util.ts, packages/playback-core/test/util.test.js
this allows 
https://stream.mux.com/Sc89iWAyNkhJ3P1rQ02nrEdCFTnfT01CZ2KmaEcxXfB008
https://stream.mux.com/Sc89iWAyNkhJ3P1rQ02nrEdCFTnfT01CZ2KmaEcxXfB008?foo=bar
instead of 
https://stream.mux.com/Sc89iWAyNkhJ3P1rQ02nrEdCFTnfT01CZ2KmaEcxXfB008.m3u8
this is needed for react-player to have a difference in the source to choose which provider.
the one where they add the .m3u8 goes to hls-video, without the extension goes to mux-player.
=> fix: allow extension less Mux m3u8 url as src

.github/workflows/ci.yml, packages/playback-core/src/index.ts, packages/playback-core/src/request-errors.ts
fixes an issue where playback is not broken yet but the player throws a fatal error making the error dialog show up while the video is playing underneath.
=> fix: respect hls.js fatal error flag if available

examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player/src/index.ts
this is needed for iOS. fix #643
=> feat: add fullscreen API on player element

examples/astro/src/pages/mux-player-react-lazy.astro, examples/astro/src/pages/mux-player-react.astro, examples/nextjs-with-typescript/pages/MuxPlayer.tsx, examples/nextjs-with-typescript/pages/MuxPlayerPosterSlot.tsx, examples/vanilla-ts-esm/public/mux-player-audio-tracks.html, examples/vanilla-ts-esm/public/mux-player-error.html, examples/vanilla-ts-esm/public/mux-player-theme-classic.html, examples/vanilla-ts-esm/public/mux-player.html, packages/mux-player-react/src/index.tsx
fix #1062
I could not reproduce the bug anymore in React but I believe this should improve it even more.
This makes sure the first attribute is set to `default-hidden-captions` in React so that is immediately available in the first render of the theme.
=> fix: default-hidden-captions order bug for React

packages/mux-player-react/src/index.tsx
closes #1124 
fix #1117 
`player-init-time` is generated differently on the server than it is on the client... which causes hydration warnings, e.g., 
```
hydration-error-info.js:63 Warning: Prop `player-init-time` did not match. Server: "1746731940341" Client: "1746731940846"
at mux-player
at eval (webpack-internal:///../../packages/mux-player-react/dist/index.mjs:138:74)
at eval (webpack-internal:///../../packages/mux-player-react/dist/index.mjs:260:71)
at main
at MuxPlayerPage (webpack-internal:///./pages/MuxPlayer.tsx:234:11)
at MyApp (webpack-internal:///./pages/_app.tsx:24:11)
at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/next/dist/shared/lib/router/adapters.js:81:11)
at ErrorBoundary (webpack-internal:///../../node_modules/next/dist/client/components/reac …
```
=> fix: suppress Mux Player React hydration warning

packages/playback-core/src/index.ts
this would only happen for a mp4 and the type error is in a try catch so it didn't cause a breaking app.
=> fix: type error in metadata response

packages/mux-player-react/src/index.tsx
To validate, use https://elements-demo-nextjs-git-fork-cjpillsbury-fix-mux-da-eeafeb-mux.vercel.app/MuxNewsPlayer and confirm video titles are different and expected for each playlist item in our Mux Data Views.
=> fix(mux-player-react): Update order of props setting so playback id always comes first to resolve session-based expectations (e.g. mux data metadata).
