muxinc/elements

- package.json
- packages/mux-audio-react/package.json
- packages/mux-audio/package.json
- packages/mux-video-react/package.json
- packages/mux-video/package.json
- packages/playback-core/package.json
- scripts/open-process.js
See solution here https://github.com/evanw/esbuild/issues/1885#issuecomment-1000866366
> Fix esbuild --watch bailing

- packages/mux-video/src/CustomVideoElement.js
The 2nd appendChild shouldn't be needed as it's appended via the template.
> Remove unneeded code

- packages/mux-player/src/template.ts
Fixes an issue with setting a custom poster image.
> Fix player poster and default poster

- packages/mux-player/src/html.ts
- packages/mux-player/src/styles.css
- packages/mux-player/src/template.ts
Adds the live indicator and fixes some things with the live small and large view. Removed the time display for live.
> Add live indicator and fixes to live views

- packages/mux-player/src/media-chrome/dialog.ts
> Center dialog text and add more line spacing

- examples/vanilla-ts-esm/public/mux-player.html
- packages/mux-player/src/index.ts
- packages/mux-player/src/utils.ts
Fixes [sc-16003]
Adds the default seek offsets of 10s to the mux-player.
> Add default 10s seek offsets

- packages/mux-player/src/media-chrome/dialog.ts
Fixes the focus going to the close button if dialog is opened.
> Fix dialog focus from attribute change

- examples/vanilla-ts-esm/public/mux-player.html
- packages/mux-player/src/index.ts
- packages/mux-player/src/styles.css
- packages/mux-player/src/template.ts
- packages/mux-player/src/utils.ts
Adds an extra small view with just a play button icon.
> Add extra small player view w/ only play button

- packages/mux-player/src/styles.css
Fixes the background color for the ranges.
> Fix range bg color

- packages/mux-player-react/README.md
First draft pass for getting some docs together for MuxPlayer (React)
> docs/mux-player-react-v1: Initial draft of docs for MuxPlayer (React).

- packages/mux-player/src/helpers.ts
- packages/mux-player/src/index.ts
- packages/mux-player/src/template.ts
- packages/mux-player/src/types.d.ts
- packages/mux-player/src/utils.ts
- packages/mux-player/test/player.test.js
I didn't add the setters/getters yet for the different tokens with update logic so it passes it down to mux-video.
7d valid tokens:
```
playback-id="bzeU5fRA47S01KDzrObYiiZvzj00j5E00dCVbt3oRzmfF00"
playback-token="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik96VU90ek1nUWhPbkk2MDJ6SlFQbU52THR4MDBnSjJqTlBxN0tTTzAxQlozelEifQ.eyJleHAiOjE2NDY0Mzg5NjEsImF1ZCI6InYiLCJzdWIiOiJiemVVNWZSQTQ3UzAxS0R6ck9iWWlpWnZ6ajAwajVFMDBkQ1ZidDNvUnptZkYwMCJ9.hWrdcJDa8FJCfVFP19oJ-9FSEVk9eB6DTOCRrucnzsrtUoZbb1OFe7swpQ38Fp3hZNNIt7-LWjdOl90TF4ucu7mhu42qyk3_i054RtmEZyQaj5Qjm3_H4sa2jLO-0QNSnOfp1A9x-fI8M_giGLg-byJPuu_eUqu1MW9bILLly_9gq8m0cNKghUa9xTMJgFmaya4XYudy5Mt2Fu72MiS3csUP3xhKlONVnGHlMRqB-dBVOgAJrayeUquAhaNY346oFBUWVM-EcAZ9G2ARtPakfy4Wpv5BsRKEGtR81P-k7EW8g27U0FKLlrvLkUz3Z-JYu53CRcJUvjkC9sDMrZLcTA" …
```
> Add signing tokens

- packages/mux-player/src/index.ts
- packages/mux-player/src/template.ts
- packages/playback-core/src/index.ts
Also, seek to liveSyncPosition on firstplay for live videos
> feat: only autoplay with the autoplay attribute

- packages/mux-player/package.json
- yarn.lock
Fixes the Safari bug that Phil discovered
> fix: add patched template-parts fork

- packages/mux-player/src/template.ts
- packages/mux-player/test/template.test.js
Fixes #165 
Adding this temporary fix for the rendering issue with dialog, captions button ?, thumbnail track ? and other elements behind a conditional.
> fix(mux-player): temp fix conditional render bug

- packages/mux-player/src/index.ts
This change adds a fix for a bug in React where the CE children of mux-player were seemingly upgraded later than mux-player.
Also adds a check whether mux-video and media-controller is successfully upgraded and logs an error if not.
> fix: child custom element mux-video upgraded after mux-player

- packages/mux-audio/package.json
- packages/mux-audio/test/player.test.js
- packages/mux-player/package.json
- packages/mux-player/src/index.ts
- packages/mux-player/test/player.test.js
- packages/mux-video/package.json
- packages/mux-video/test/player.test.js
this change clears the dialog state when changing playbackId
> fix: clear some state on playbackId change

- packages/mux-player/src/errors.ts
- packages/mux-player/src/index.ts
- packages/mux-player/test/errors.test.js
- packages/mux-player/test/player.test.js
- packages/playback-core/src/errors.ts
- packages/playback-core/src/index.ts
also fixes an issue with random failing tests
> fix: make mux-video errors more uniform, fix async

- packages/mux-player/package.json
- packages/mux-player/src/html.ts
- packages/mux-player/src/logger.ts
- yarn.lock
✅ Improve Mux Player logger
✅ Media Chrome bugfix for fullscreen
Thoughts on improving the logger to include the player version number?
> Improve Mux Player logger + Media Chrome bugfix for fullscreen

- packages/mux-player/README.md
- packages/mux-player/lang/en.json
- packages/mux-player/src/index.ts
> update mux-player signed url docs, add a quick check for it

- examples/vanilla-ts-esm/public/mux-player.html
- packages/mux-player/src/media-theme-mux/styles.css
- packages/mux-player/src/template.ts
> feat: vertical align progress bar and improve second color background

- packages/mux-player/src/constants.ts
- packages/mux-player/src/helpers.ts
- packages/mux-player/src/index.ts
- packages/mux-player/src/media-theme-mux/media-theme-mux.ts
- packages/mux-player/src/template.ts
- packages/playback-core/src/index.ts
Unadvertised MVP implementation of DVR.
> feat(dvr): Initial effort for DVR support.

- scripts/publish.sh
canary releases were failing :(
> chore: fix canary release

- packages/mux-uploader/src/index.ts
`mux-uploader` is currently not accessible to screen readers particularly around upload states 😢 
This PR adds initial screen reader functionality for VoiceOver 🌈 
- Announces upload completion regardless if progress bar is in focus ✅ 
- Announces upload error regardless if progress bar is in focus ✅ 
- Announces current progress when progress bar is in focus ✅ 
- Ticks when progress bar is in focus and is uploading ✅ 
- Briefly tested with ChromeVox but the browser keeps crashing. Not sure why yet.
- Normally, when contents change within a live region, it can be announced. However, it seems like when changes to contents happen within different upload events, such as progress and completion, one won't be read.
- Currently dealing with this using a combination of `innerHTML` and `sr-only` …
> fix(mux-uploader): Make progress, errors, completion accessible to VoiceOver

- packages/mux-audio-react/package.json
- packages/mux-player-react/package.json
- packages/mux-video-react/package.json
> Update React peer deps

- examples/vanilla-ts-esm/public/index.html
- examples/vanilla-ts-esm/public/mux-player-audio.html
- examples/vanilla-ts-esm/public/mux-player.html
- packages/mux-player/package.json
- packages/mux-player/src/media-theme-mux/styles.css
- packages/mux-player/src/template.ts
- yarn.lock
Related to https://github.com/muxinc/media-chrome/pull/255
Test url: https://elements-demo-vanilla-git-fork-luwes-new-timerange-mux.vercel.app/mux-player.html
> fix: upgrade MC to v0.8.0 and adjust time range styles

- packages/mux-player/package.json
- yarn.lock
https://github.com/muxinc/media-chrome/pull/271
fixes jumpy time range with playbackRate other than 1
> fix: upgrade MC v0.8.1

- CODEOWNERS
> sc-35838 add codeowners

- examples/nextjs-with-typescript/pages/MuxUploader.tsx
- packages/mux-uploader-react/README.md
- packages/mux-uploader-react/src/index.tsx
- packages/mux-uploader/README.md
- packages/mux-uploader/src/index.ts
- Fixes empty event data being passed through for `attempt` (now `chunkAttempt`) and `chunkSuccess` events ➕ 
- Make naming convention for event data passed through in custom events more consistent ✨ 
- Updates related READMEs 🌈 
- Updates related examples 🌈 
- GitHub: https://github.com/muxinc/elements/pull/304/files#r927159152
- Slack: https://mux.slack.com/archives/C032TQ30ARL/p1658443853194809
- React example ✅ 
- Next.js example ✅ 
- Vanilla example ✅
> [Docs/mux-uploader] Improve event naming, casing, and fix null data passed through

- examples/nextjs-with-typescript/pages/MuxUploader.tsx
- examples/vanilla-ts-esm/public/mux-uploader-full.html
- packages/mux-uploader-react/README.md
- packages/mux-uploader-react/src/index.tsx
- packages/mux-uploader/README.md
- packages/mux-uploader/src/index.ts
Based on my experience integrating the uploader into `stream.new`, consumers could benefit from the following:
- Adds `uploadstart` event ➕ 
- Adds `--button-border` and `--button-padding` CSS variables ➕ 
- Related `README` and example updates ✨
> Feat(mux uploader): CSS variable, docs, and event improvements

- packages/mux-video/README.md
> shorten prefer-mse explanation

- examples/nextjs-with-typescript/pages/MuxAudio.tsx
- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- examples/nextjs-with-typescript/pages/MuxUploader.tsx
- examples/nextjs-with-typescript/pages/MuxVideo.tsx
- examples/nextjs-with-typescript/pages/_app.js
- examples/nextjs-with-typescript/pages/mux-audio.tsx
- examples/nextjs-with-typescript/pages/mux-player.tsx
- examples/nextjs-with-typescript/pages/mux-video.tsx
- examples/nextjs-with-typescript/styles.css
- packages/mux-player-react/src/index.tsx
- packages/mux-player/src/index.ts
- packages/mux-player/src/template.ts
Supercedes https://github.com/muxinc/elements/pull/326
> chore: spruce up Next.js examples & add controlsList option

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- packages/mux-audio-react/package.json
- packages/mux-audio/package.json
- packages/mux-elements-codemod/package.json
- packages/mux-player-react/package.json
- packages/mux-player/package.json
- packages/mux-uploader-react/package.json
- packages/mux-uploader/package.json
- packages/mux-video-react/package.json
- packages/mux-video/package.json
- packages/playback-core/package.json
Worth a shot to see if the dist folders are picked up this way. If not I'm gonna roll up my pant legs 😅
> ci: try fix hangup w/ 1 build for releases

- .github/workflows/ci.yml
- .gitignore
- package.json
- turbo.json
- yarn.lock
trying out Turborepo for faster builds, tests. also caches remotely for the Vercel example apps.
---
We can fully replace Lerna with a publish flow like we use for canaries if we like.
> ci: try out turborepo

- packages/mux-player/src/media-theme-mux/media-theme-mux.ts
fixes the issue where the title would not render again after removal.
> fix: template parts issue

- packages/mux-player/package.json
- yarn.lock
fixes scrolling on hotkeys and updating progress bar when media is loading
> fix: update to media-chrome 0.10.2

- examples/vanilla-ts-esm/public/mux-player.html
- packages/mux-player/src/index.ts
- packages/mux-player/src/video-api.ts
- packages/mux-player/test/player.test.js
this change unloads the player when the playback id is removed or when using src, the src is removed.
> fix: src unloading

- packages/mux-video-react/src/index.tsx
> fix: allow autoplay to change in mux-video-react

- examples/nextjs-with-typescript/pages/MuxPlayerIframe.tsx
- examples/nextjs-with-typescript/pages/index.tsx
- packages/mux-player/src/media-theme-mux/styles.css
Depends on https://github.com/muxinc/media-chrome/pull/311
> fix: hide fullscreen button when fullscreen is unavailable

- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- examples/nextjs-with-typescript/styles.css
Before dark colorscheme:
After dark colorscheme:
Before light colorscheme:
After light colorscheme:
> Update some of the nextjs styles for dark colorscheme and overflow

- packages/mux-player/package.json
- packages/mux-player/src/index.ts
- packages/mux-player/src/media-chrome/time-display.ts
- packages/mux-player/src/media-theme-mux/media-theme-mux.ts
- packages/mux-player/src/media-theme-mux/styles.css
- packages/mux-player/src/styles.css
- packages/mux-player/src/template.ts
- packages/mux-player/src/types.d.ts
- packages/mux-player/test/template.test.js
- yarn.lock
Depends on https://github.com/muxinc/media-chrome/pull/320 for the disabled buttons functionality. This PR adds styles and the attributes as appropriate.
> Disable some controls when there isn't a playback-id

- packages/.eslintrc.json
- packages/mux-audio-react/package.json
- packages/mux-audio/package.json
- packages/mux-elements-codemod/package.json
- packages/mux-player/package.json
- packages/mux-video-react/package.json
- packages/mux-video/package.json
- packages/playback-core/package.json
- shared/castable-video/package.json
- shared/polyfills/package.json
- yarn.lock
adds eslint to some more packages and upgrades eslint
> tools: eslint update

- packages/mux-player/src/index.ts
- packages/mux-player/test/player.test.js
allow removing a src with a nil value
> fix: playback-id or src nil value

- packages/mux-player/src/index.ts
- packages/mux-player/src/media-theme-mux/media-theme-mux.ts
- packages/mux-player/src/template.ts
- packages/mux-player/test/template.test.js
Alternative to https://github.com/muxinc/elements/pull/427
> fix: disable buttons behind dialog

- packages/mux-player-react/src/lazy.tsx
Also fixes issue where placeholder had no background-position set at all
> fix: observe media-object css variables on lazy placeholder

- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- packages/mux-player-react/src/common/utils.ts
- packages/mux-player/src/video-api.ts
> fix: playbackRate not working on mux-player-react

- examples/vanilla-ts-esm/public/mux-player-audio.html
- packages/mux-player/package.json
- packages/mux-player/src/index.ts
- packages/mux-player/src/media-theme-mux/media-theme-mux.ts
- packages/mux-player/src/media-theme-mux/styles.css
- packages/mux-player/src/styles.css
- packages/mux-player/src/template.ts
- packages/mux-player/test/template.test.js
- shared/assets/media-assets.json
- yarn.lock
- default vertical design is not included yet
> feat: first iteration on player design update

- examples/svelte-kit/package.json
- packages/.eslintrc.json
- shared/.eslintrc.json
- shared/castable-video/castable-video.js
- yarn.lock
related to #308
this first commit fixes a memory leak caused by the Set in CastableVideo but there appears another issue for MuxVideoReact. still digging in that one
> fix: memory leak of detached media elements in CastableVideo

- packages/playback-core/package.json
- yarn.lock
Might resolve #541 build issue in Svelte
> bump to latest hls.js (1.3.1)

- packages/mux-player/src/media-theme-mux.html
> fix: bring back play button to the control bar for small player size

- examples/vanilla-ts-esm/public/mux-player-theme.html
- packages/mux-player/package.json
- packages/mux-player/src/media-theme-mux.html
- packages/mux-player/src/styles.css
- turbo.json
- yarn.lock
Requires https://github.com/muxinc/media-chrome/pull/502
> fix: use Media Chrome display CSS vars

- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- examples/nextjs-with-typescript/pages/MuxPlayerTheme.tsx
- packages/mux-player/package.json
- packages/mux-player/themes/micro.js
- packages/mux-player/themes/microvideo.js
- yarn.lock
requires https://github.com/muxinc/media-chrome/pull/504
> fix: rename Micro to Microvideo

- packages/mux-player/src/errors.ts
- packages/mux-player/src/index.ts
- packages/mux-player/src/logger.ts
- packages/mux-player/src/types.d.ts
- packages/mux-player/test/errors.test.js
- packages/playback-core/package.json
- packages/playback-core/src/errors.ts
- packages/playback-core/src/index.ts
- types/mux-embed.d.ts
- yarn.lock
* Mux Data Dashboard will group errors much better this way
> Player error context

- packages/mux-player/src/media-theme-mux.html
related https://github.com/muxinc/media-chrome/pull/494
> fix: live view due targetLiveWindow change

- packages/mux-player/package.json
- packages/mux-player/src/index.ts
- packages/mux-player/test/player.test.js
- yarn.lock
fixes the cue position logic that would not work after a theme change
> fix: delegate events, lazy controller for cue pos

- packages/mux-uploader/src/layouts/block.ts
- packages/mux-uploader/src/mux-uploader.ts
- packages/mux-uploader/test/uploader.test.js
This changes mux-uploader attrs from smooshed to kebab style
> chore(mux-uploader): Change to kebab attrs

- packages/mux-uploader-react/src/index.tsx
- packages/mux-uploader/src/mux-uploader.ts
- packages/mux-uploader/test/uploader.test.js
Introduces a setter for `chunkSize` which is passed on to Upchunk during upload init
> feat(mux-uploader): introduce chunkSize

- packages/playback-core/src/index.ts
NOTE: This is actually a bug in browsers based on a previously ambiguous definition in the HTML spec. For context, see:
- https://github.com/video-dev/hls.js/issues/5168
- https://html.spec.whatwg.org/multipage/media.html#reaches-the-end (referenced in the issue, above)
Additionally, I've updated the "pseudo-ended" logic to not apply when the media element is looping, since (again, per spec), that media should not ever "end".
> fix(playback-core): Apply pseudo-ended logic on seeked, even if paused.

- package.json
- yarn.lock
> chore: upgrade turbo

- packages/mux-active-viewer-count/package.json
- packages/mux-audio-react/package.json
- packages/mux-audio/package.json
- packages/mux-player-react/package.json
- packages/mux-player/package.json
- packages/mux-uploader-react/package.json
- packages/mux-uploader/package.json
- packages/mux-video-react/package.json
- packages/mux-video/package.json
- packages/playback-core/package.json
If I understand correctly, I think the previous PR had the wrong type field... I completely forgot to fix that. I believe this will eliminate any errors.
> Fix type field path

- examples/vanilla-ts-esm/public/index.html
- examples/vanilla-ts-esm/public/mux-player-renditions.html
- packages/mux-player/src/index.ts
- packages/mux-player/src/video-api.ts
- packages/mux-video/package.json
- packages/mux-video/src/index.ts
- packages/playback-core/package.json
- packages/playback-core/src/index.ts
- packages/playback-core/src/renditions.ts
- packages/playback-core/src/types.ts
- shared/assets/media-assets.json
- yarn.lock
Media Tracks + renditions API at https://github.com/muxinc/media-tracks
test url: https://elements-demo-vanilla-git-fork-luwes-renditions-mux.vercel.app/mux-player-renditions.html
> feat: implement renditions API

- packages/mux-player/src/template.ts
- packages/mux-player/test/template.test.js
for progressive enhancement and using responsive images. it will also load
the poster faster as it doesn't have to wait on
the mux-player JS bundle to load
> feat: add a poster slot for progressive enhancement

- examples/vanilla-ts-esm/public/mux-player-audio-tracks.html
- packages/mux-player/package.json
- packages/mux-player/src/styles.css
- packages/mux-player/src/themes/classic/classic.html
- packages/playback-core/src/media-tracks.ts
- yarn.lock
- prevent duplicate audio tracks from different groups
- adds audio track selectmenu
> feat: add audio track select menu

- packages/playback-core/src/index.ts
- packages/playback-core/src/media-tracks.ts
related https://github.com/video-dev/hls.js/issues/5749
> fix: quality switch on alt audio

- packages/mux-active-viewer-count/package.json
- packages/mux-audio-react/package.json
- packages/mux-audio/package.json
- packages/mux-player-react/package.json
- packages/mux-player/package.json
- packages/mux-uploader-react/package.json
- packages/mux-uploader/package.json
- packages/mux-video-react/package.json
- packages/mux-video/package.json
I didn't spend a ton of time brainstorming what other keywords should be in these lists, but figured at least getting the ball rolling could help. Noticed we were missing these when I didn't see us come up in some searches, so hopefully this helps with some discoverability.
> chore: Add NPM keywords

- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- packages/mux-player/src/themes/2023/2023.html
> fix: improve 2023 icons

- packages/mux-player/src/index.ts
- packages/mux-player/src/themes/classic/classic.html
- packages/mux-player/src/themes/gerwig/gerwig.html
also fixes a couple css selector regressions
> feat(mux-player)!: switch to new default theme

- packages/mux-player-react/README.md
- packages/mux-player/README.md
- packages/mux-player/UPGRADING_V1_to_V2.md
- Don't merge yet til blog post goes out
> Updating markdown files for 2.0 release

- examples/vanilla-ts-esm/package.json
- examples/vanilla-ts-esm/public/index.html
- examples/vanilla-ts-esm/public/mux-player-theme-classic.html
- examples/vanilla-ts-esm/src/mux-player-classic-theme.ts
- examples/vanilla-ts-esm/src/mux-player-gerwig-theme.ts
- yarn.lock
now that Gerwig is the default theme, make classic an alternative theme example.
test url: https://elements-demo-vanilla-git-fork-luwes-demo-vanilla-theme-mux.vercel.app/
> example: update alternative theme to classic

- packages/mux-player/package.json
- packages/mux-player/src/themes/gerwig/gerwig.html
- yarn.lock
> fix: upgrade media-chrome 1.4.5 + rate row style

- packages/mux-player/src/themes/gerwig/gerwig.html
- yarn.lock
> fix(mux-player): add controller CSS part 

- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- examples/nextjs-with-typescript/pages/MuxVideo.tsx
- packages/mux-audio-react/src/index.tsx
- packages/mux-audio/src/index.ts
- packages/mux-player-react/src/index.tsx
- packages/mux-player/src/index.ts
- packages/mux-video-react/src/index.tsx
- packages/mux-video/src/index.ts
- packages/playback-core/src/index.ts
- packages/playback-core/src/types.ts
🤫 seeeecret config.
fixes #792
> fix: Adding unofficial _hlsConfig to media elements and playback core.

- packages/mux-audio/package.json
- packages/mux-video/package.json
- yarn.lock
Upgrades custom-media-element in all dependencies
> fix: upgrade custom-media-element

- package.json
- packages/mux-video/package.json
- yarn.lock
related PR https://github.com/muxinc/custom-media-element/pull/18
> fix(custom-media-element): fix chapters & metadata tracks

- packages/mux-player/package.json
- packages/mux-player/src/themes/classic/classic.html
- packages/mux-player/src/themes/gerwig/gerwig.html
- yarn.lock
with the new MC v3 the timerange preview required some small UI updates for the shifting arrow.
also adds some polish discussed in our doc Mux player polishing.
> fix: polish new time preview w/ shifting arrow

- examples/vanilla-ts-esm/public/mux-player-renditions.html
- packages/mux-player/src/themes/gerwig/gerwig.html
See https://larsenwork.com/easing-gradients/
After:
Before:
> fix: polish, use easing gradients

- packages/mux-player/package.json
- yarn.lock
> fix(mux-player): More cleanup for DVR in media chrome

- packages/playback-core/src/index.ts
In order to support for "media ui extensions" such as "stream type" in our media elements across as many playback environments as possible, we independently fetch and parse HLS playlists, even when playback of HLS media is managed natively by the Safari `HTMLMediaElement`. We also aim to respect developer preferences such as `preload="none"`. To accomplish this, we previously relied on waiting for the `'loadstart'` event to be dispatched before initiating our fetching logic for cases where `preload="none"`. Unfortunately, per spec, `'loadstart'` will be dispatched regardless of `preload` state. Both Chrome and Safari comply with the specification (Firefox appears to deviate from the spec to get closer to the "spirit of the law," but this also results in cross-browser inconsistencies).
For …
> fix(playback-core): preload=none not respected for playlist stream info fetching with native safari playback.

- packages/mux-uploader/src/layouts/block.ts
- packages/mux-uploader/src/mux-uploader.ts
For testing, go to https://elements-demo-vanilla-git-fork-cjpillsbury-feat-mux-9cf70f-mux.vercel.app/mux-uploader-simple.html and use Dev Tools to manually change `height` style value.
> feat(mux-uploader): Clean up styling and templating code for mux-uploader for (re)sizing.

- examples/nextjs-with-typescript/app/page-state/index.ts
- examples/nextjs-with-typescript/components/ComponentCodeRenderer.tsx
- examples/nextjs-with-typescript/components/URLPathRenderer.tsx
- examples/nextjs-with-typescript/components/renderers.tsx
- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- examples/nextjs-with-typescript/pages/MuxUploader.tsx
- examples/nextjs-with-typescript/styles.css
- packages/mux-uploader-react/src/index.tsx
- packages/mux-uploader/src/mux-uploader.ts
Primary purpose of this PR is to pull out all of the configuration logic, URL updates, component example generation, etc. into abstracted code and use it for both MuxPlayer and MuxUploader pages, but since there are (minor) src code changes, naming as a fix branch.
**Smoke testing updated pages**
- MuxPlayer - https://elements-demo-nextjs-git-fork-cjpillsbury-chore-next-2001f5-mux.vercel.app/MuxPlayer
- MuxUploader - https://elements-demo-nextjs-git-fork-cjpillsbury-chore-next-2001f5-mux.vercel.app/MuxUploader
> fix(mux-uploader, mux-uploader-react): Minor cleanup

- packages/mux-player/src/video-api.ts
> fix: attach events on null media property

- packages/mux-audio-react/package.json
- packages/mux-player-react/package.json
- packages/mux-uploader-react/package.json
- packages/mux-video-react/package.json
this PR allows the react elements to be used with react 19
> fix: mark React 19 as peerdep

- packages/playback-core/src/index.ts
> fix: Sentry seekable index error

- packages/playback-core/package.json
- yarn.lock
> fix(playback-core): upgrade mux-embed

- README_INTERNAL.md
- packages/mux-player-react/src/index.tsx
- packages/mux-player/src/html.ts
Fool me once...
BREAKING CHANGE: Retrospective breaking change for tooltips pr
> chore(mux-player, mux-player-react)!: breaking change take 2

- packages/playback-core/src/text-tracks.ts
fixes a bug when starting playback after preload none the chapters disappear
> fix: chapters disappearing after preload none

- examples/nextjs-with-typescript/app/page-state/index.ts
- examples/nextjs-with-typescript/components/renderers.tsx
- examples/nextjs-with-typescript/pages/MuxPlayer.tsx
- Handles complex objects as state/player/renderer values (depth of 1 keys)
- Adds UI Renderers/Inputs for
- all tokens
- preferPlayback
Demo Page: https://elements-demo-nextjs-git-fork-cjpillsbury-chore-next-1399d7-mux.vercel.app/MuxPlayer
> chore: nextjs mux player improvements

- examples/vanilla-ts-esm/public/mux-player.html
- packages/mux-audio/package.json
- packages/mux-video/package.json
- yarn.lock
fix #936
1. go to https://elements-demo-vanilla-git-fork-luwes-fix-load-tracks-mux.vercel.app/mux-player.html
2. hit play button
3. view storyboard by hovering over timeline
4. press load new playback id button
5. hit play button
6. check that storyboard was updated to new video
> fix: tracks updating after load new playback id

- packages/mux-player/package.json
- yarn.lock
https://github.com/muxinc/player.style/releases/tag/player.style%400.1.0
> fix: upgrade player.style 0.1.0

- .github/release-please/release-please-config.json
- README.md
- README_INTERNAL.md
we can easily sync the custom element and react versions now with this release please plugin.
> chore: linked versions for player, video, audio, uploader

- packages/mux-player/src/template.ts
> fix: add missing menu part

- examples/vanilla-ts-esm/package.json
- package-lock.json
- package.json
- packages/mux-active-viewer-count/package.json
- packages/mux-audio-react/package.json
- packages/mux-audio/package.json
- packages/mux-elements-codemod/package.json
- packages/mux-player-react/package.json
- packages/mux-player/package.json
- packages/mux-uploader-react/package.json
- packages/mux-uploader/package.json
- packages/mux-video-react/package.json
- packages/mux-video/package.json
- packages/playback-core/package.json
- scripts/esbuilder/package.json
- castable-video https://github.com/muxinc/media-elements/releases/tag/castable-video%401.1.5
> fix: upgrade dependencies (castable-video, ...)

- package-lock.json
- packages/mux-player/package.json
https://github.com/muxinc/media-chrome/releases/tag/v4.9.0
fix #1062
> fix: upgrade media-chrome

- package-lock.json
- packages/mux-audio/package.json
- packages/mux-player/package.json
- packages/mux-video/package.json
- packages/mux-video/test/index.test.js
- packages/playback-core/package.json
- packages/playback-core/src/media-tracks.ts
- turbo.json
related https://github.com/video-dev/hls.js/pull/7368
> fix: upgrade hls.js to 1.6.6, rm workaround MTA (multi-track audio)

- packages/mux-player/src/themes/news/news.html
adds some small improvements for very small player sizes to the news theme
https://elements-demo-nextjs-git-fix-news-theme-responsive-mux.vercel.app/MuxPlayerAds
> fix: news theme responsive issues
